  function chives(chinchilla, ibex) {
    return _0xed29 = function (boar, llama) {
      var capybara; // _0x406241
      
          boar = boar - 0xfa;
      capybara = raccoon[boar];
      return capybara;
    }, 
    chives(chinchilla, ibex);
  }
  var raccoon; // _0xfaae
  var hamster; // _0x3218dc
  
  raccoon = ['Ακύρωση', 'Προεπιλογή Συστήματος', 'Προτιμήσεις Health Report', '{APP_NAME} Health Report', 'Κοινοποίηση ανώνυμων πληροφοριών σχετικά με το πώς χρησιμοποιώ το {APP_NAME}', 'Προκειμένου να βελτιώσουμε το {APP_NAME}, στέλνουμε περιοδικά περιορισμένα, <strong>ανώνυμα</strong> στατιστικά στοιχεία στην Adobe σχετικά με το πώς χρησιμοποιείς το {APP_NAME}. Αυτές οι πληροφορίες βοηθάνε στην καταχώρηση προτεραιοτήτων στα χαρακτηριστικά,στην εύρεση σφαλμάτων και στον εντοπισμό προβλημάτων χρηστικότητας.<br><br>Μπορείς να δεις τα δεδομένα σου ή να επιλέξεις να μην μοιραστείς κάποια επιλέγοντας <strong>Help > Health Report</strong>.<br><br><a href=\'https://github.com/adobe/brackets/wiki/Health-Data\'>Μάθε περισσότερα για το {APP_NAME} Health Report</a>', 'Χρόνος', 'Πρόοδος', 'Αρχικό Χρώμα', 'Μορφή RGBa', '{0} (Χρησιμοποιήθηκε {1} φορά)', '{0} (Χρησιμοποιήθηκε {1} φορές)', 'Πήγαινε στον Ορισμό', 'Προβολή Υποδείξεων Παραμέτρων', '<χωρίς παραμέτρους>', 'JSLint', 'Γρήγορη Προβολή στο Hover', 'Πρόσφατα Project', '47833RNnArT', '11AhfgLw', '1278278vVRLWm', '1267807MkrsoC', '1QIOjFU', '290296jQZOik', '892737xytIBp', '625418RLcFIB', '1537266NDAhpg', '(error {0})', 'Το αρχείο δεν βρέθηκε.', 'Το αρχείο δεν μπορεί να διαβαστεί.', 'Αρχεία που ξεπερνούν τα {0} MB δεν μπορούν να ανοίξουν στο {APP_NAME}.', 'Το αρχείο έχει τροποποιηθεί εκτός του {APP_NAME}.', 'Ο φάκελος δεν μπορεί να τροποποιηθεί.', 'Αυτό το αρχείο ή ο φάκελος υπάρχουν ήδη.', 'Αρχείο', 'Φάκελος', 'Ονόματα αρχείων', 'Όνομα αρχείου', 'Όνομα φακέλου', 'Σφάλμα φόρτωσης project', 'Σφάλμα προέκυψε κατά τη διαδικασία εμφάνισης του παραθύρου ανοίγματος αρχείου. (error {0})', 'Σφάλμα προέκυψε κατά τη διαδικασία φόρτωσης του φακέλου <span class=\'dialog-filename\'>{0}</span>. (error {1})', 'Σφάλμα ανοίγματος αρχείου', 'Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος του αρχείου <span class=\'dialog-filename\'>{0}</span>. {1}', 'Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος των παρακάτω αρχείων:', 'Σφάλμα επαναφόρτωσης αλλαγών από το δίσκο', 'Σφάλμα προέκυψε κατά τη διαδικασία επαναφόρτωσης του αρχείου <span class=\'dialog-filename\'>{0}</span>. {1}', 'Σφάλμα αποθήκευσης αρχείου', 'Σφάλμα προέκυψε κατά τη διαδικασία αποθήκευσης του αρχείου <span class=\'dialog-filename\'>{0}</span>. {1}', 'Σφάλμα μετονομασίας αρχείου', 'Σφάλμα διαγραφής αρχείου', 'Σφάλμα προέκυψε κατά τη διαδικασία διαγραφής του αρχείου <span class=\'dialog-filename\'>{0}</span>. {1}', 'Τα όνομα αρχείων δεν μπορούν να περιέχουν τους ακόλουθους χαρακτήρες: {0} ή οποιεσδήποτε system reserved λέξεις.', 'Σφάλμα δημιουργίας {0}', 'Σφάλμα προέκυψε κατά τη διαδικασία δημιουργίας του {0} <span class=\'dialog-filename\'>{1}</span>. {2}', 'Ουπς! Το {APP_NAME} δεν τρέχει ακόμα σε browsers.', 'To {APP_NAME} είναι γραμμένο σε HTML, αλλά αυτή τη στιγμή τρέχει σαν native εφαρμογή έτσι ώστε να μπορείτε να επεξεργαστείτε τοπικά αρχεία. Παρακαλούμε να χρησιμοποιήσετε το application shell στο <b>github.com/adobe/brackets-shell</b> repo για να τρέξετε το {APP_NAME}.', 'Ο μέγιστος αριθμός αρχείων έχει καταχωρηθεί index. Λειτουργίες που ψάχνουν αρχεία στο index μπορεί να μην δουλεύουν σωστά.', 'Σφάλμα ανοίγματος browser', 'Σύνδεση στον Browser', 'Για να συνδεθεί το Live Preview, ο Chrome πρέπει να επανεκκινηθεί με το remote debugging (απομακρυσμένη αποσφαλμάτωση) ενεργοποιημένο.<br /><br />Θέλετε να επανεκκινήσετε τον Chrome και να ενεργοποιήσετε το remote debugging;', 'Για να ανοίξετε το Live Preview με ένα αρχείο από κάποιον server, πρέπει να προσδιορίσετε μια διεύθυνση (Base URL) για αυτό το project.', 'Σφάλμα κατά τη διαδικασία εκκίνησης του HTTP server για την άμεση επεξεργασία αρχείων. Παρακαλούμε προσπαθήστε ξανά.', 'Για περισσότερες πληροφορίες δείτε εδώ: <a href=\'{0}\' title=\'{0}\'>Troubleshooting Live Development connection errors</a>.', 'Live Preview', 'Live Preview: Σύνδεση…', 'Live Preview: Εκκίνηση…', 'Αποσύνδεση Live Preview', 'Live Preview (κάντε αποθήκευση για να ανανεωθεί)', 'Live Preview (αδυναμία ανανέωσης λόγο συντακτικού λάθους)', 'Το Live Preview ακυρώθηκε επειδή τα developer tools του browser ανοίχτηκαν', 'Το Live Preview ακυρώθηκε επειδή η σελίδα στον browser έκλεισε', 'Το Live Preview ακυρώθηκε επειδή ο browser πήγε σε μια σελίδα που δεν είναι μέρος του τρέχων project', 'Το Live Preview ακυρώθηκε. Δεν ξέρουμε γιατί. ({0})', 'Θέλετε να αποθηκεύσετε τις αλλαγές που κάνατε στο έγγραφο <span class=\'dialog-filename\'>{0}</span>?', 'Εξωτερικές Αλλαγές', 'Είστε σίγουρος ότι θέλετε να διαγράψε το αρχείο <span class=\'dialog-filename\'>{0}</span>?', 'Είστε σίγουρος ότι θέλετε να διαγράψετε τον φάκελο <span class=\'dialog-filename\'>{0}</span>?', 'Το <span class=\'dialog-filename\'>{0}</span> έχει τροποποιηθεί στο δίσκο, αλλά υπάρχουν και μη αποθηκευμένες αλλαγές στο {APP_NAME}.<br /><br />Ποια έκδοση θέλετε να κρατήσετε;', 'Το <span class=\'dialog-filename\'>{0}</span> έχει διαγραφεί στον δίσκο, αλλά έχει μη αποθηκευμένες αλλαγές στο {APP_NAME}.<br /><br />Θέλετε να κρατήσετε τις αλλαγές σας;', '{0} από {1}', 'Δεν βρέθηκαν αποτελέσματα', 'Εύρεση…', 'Αντικατάσταση με…', 'Ναι', 'Όχι', 'Όλα…', 'Επόμενη Αντιστοιχία', 'Προηγούμενη Αντιστοιχία', 'Άνοιγμα Αρχείου', 'Αποθήκευση Αρχείου', 'Επίλεξε ένα φάκελο', 'Έχετε την τελευταία έκδοση!', 'Αντικατάσταση', 'αρχείο', 'αρχεία', 'αντιστοιχία', 'αντιστοιχίες', 'Πάνω από ', '{0}&mdash;{1}', '<span class=\'dialog-filename\'>{0}</span> {2} <span class=\'dialog-path\'>{1}</span>', 'Σφάλμα λήψης πληροφοριών αναβάθμισης', 'Φόρτωση…', 'Αρχεία Εργασίας', 'Ctrl', 'Shift', 'Space', ' — επιλεγμένη {0} στήλη', ' — επιλεγμένη {0} γραμμή', ' — {0} επιλογές', 'Κάντε κλικ για να αλλάξετε τις εσοχές (indentation) σε κενά', 'Κάντε κλικ για να αλλάξετε τις εσοχές (indentation) σε tabs', 'Κάντε κλικ για να αλλάξετε τον αριθμό των κενών στις εσοχές', 'Κάντε κλικ για να αλλάξετε το πλάτος του tab', 'Μέγεθος Tab:', '— {0} Γραμμή', '— {0} Γραμμές', 'Οι επεκτάσεις απενεργοποιήθηκαν', 'Κάνε κλικ για να αλλάξεις τον τύπο του αρχείου', '1 {0} Σφάλμα', '{1} {0} Σφάλματα', 'Το Linting είναι απενεργοποιημένο', 'Δεν υπάρχει linter διαθέσιμος για {0}', 'Δεν υπάρχει κάτι για να γίνει lint', '{0} τερμάτισε με σφάλμα: {1}', 'Νέο', 'Νέο Αρχείο', 'Νέος Φάκελος', 'Άνοιγμα…', 'Άνοιγμα Φακέλου…', 'Κλείσιμο Όλων', 'Κλείσιμο Λίστας', 'Κλείσιμο Άλλων απο πάνω', 'Κλείσιμο Άλλων από κάτων', 'Αποθήκευση Ως…', 'Μετονομασία', 'Διαγραφή', 'Εγκατάσταση Επέκτασης (Extension)…', 'Διαχείρηση Επεκτάσεων…', 'Ανανέωση Δέντρου Αρχείων', 'Κλείσιμο', '΄Εξοδος', 'Επεξεργασία', 'Επανάληψη', 'Επικόλληση', 'Επιλογή Όλων', 'Προσθήκη κέρσοσα στην επόμενη γραμμή', 'Προσθήκη κέρσοσα στην προηγούμενη γραμμή', 'Εύρεση', 'Εύρεση σε Αρχεία', 'Εύρεση σε…', 'Εύρεση Προηγούμενου', 'Εσοχή', 'Δημιουργία Αντιγράφου', 'Διαγραφή Γραμμής', 'Εναλλαγή Σχολίου Γραμμής', 'Εναλλαγή Σχολίου Block', 'Μετακίνηση Γραμμής Πάνω', 'Μετακίνηση Γραμμής Κάτω', 'Δημιουργία Γραμμής από πάνω', 'Δημιουργία Γραμμής από κάτω', 'Αυτόματο Κλείσιμο Αγκίστρων', 'Προβολή', 'Απόκρυψη Πλευρικής Εργαλειοθήκης', 'Αύξηση Μεγέθους Γραμματοσειράς', 'Μείωση Μεγέθους Γραμματοσειράς', 'Επαναφορά Μεγέθους Γραμματοσειράς', 'Κύλιση Γραμμής Πάνω', 'Κύλιση Γραμμής Κάτω', 'Αναδίπλωση Λέξης', 'Επισήμανση Live Preview', 'Lint Αρχείων κατά την Αποθήκευση', 'Ταξινόμηση κατά Σειρά Προσθήκης', 'Ταξινόμηση κατά Όνομα', 'Αυτόματη Ταξινόμηση', 'Πλοήγηση', 'Γρήγορο Άνοιγμα', 'Πήγαινε στη γραμμή', 'Γρήγορη Αναζήτηση Ορισμού', 'Πήγαινε στο Πρώτο Σφάλμα/Προειδοποίηση', 'Γρήγορη Επεξεργασία', 'Γρήγορα Έγγραφα', 'Νέος Κανόνας', 'Επόμενο Έγγραφο', 'Προηγούμενο Έγγραφο', 'Επόμενο έγγραφο στην λίστα', 'Προηγούμενο έγγραφο στην λίστα', 'Προβολή στο Δέντρο Αρχείων', 'Προβολή στο Λειτουργικό Σύστημα', 'Βοήθεια', 'Έλεγχος για Αναβαθμίσεις', 'Πώς να Χρησιμοποιήσετε το {APP_NAME}', 'Υποστήριξη {APP_NAME}', 'Release Notes', '{APP_TITLE} Αρχική σελίδα', '{TWITTER_NAME} στο Twitter', 'Σχετικά με το {APP_TITLE}', 'experimental build', 'development build', 'Αποθήκευση', 'Επαναφόρτωση από τον Δίσκο', 'Διατήρηση Αλλαγών στον Επεξεργαστή', 'Κλείσιμο (Να Μην Αποθηκευτεί)', 'Επανεκκίνηση Chrome', 'Σχετικά', 'Πληροφορίες, όροι και οι προϋποθέσεις που αφορούν λογισμικό τρίτων κατασκευαστών βρίσκονται στο <a href=\'{ADOBE_THIRD_PARTY}\'>{ADOBE_THIRD_PARTY}</a> και ενσωματώνονται εδώ με αναφορά.', 'Documentation και πηγαίος κώδικας στο <a href=\'https://github.com/adobe/brackets/\'>https://github.com/adobe/brackets/</a>', 'Φτιαγμένο με ❤ και JavaScript από:', 'Τα MDN Docs και το MDN γραφικό logo είναι αδειοδοτημένα κάτω από την άδεια Creative Commons Attribution, <a href=\'{MDN_DOCS_LICENSE}\'>CC-BY-SA 2.5 Unported</a>.', 'Υπάρχει ένα νέο build του {APP_NAME} διαθέσιμο! Πατήστε εδώ για λεπτομέρειες.', 'Διαθέσιμη Αναβάθμιση', 'Ψιτ, υπάρχει ένα νέο build του {APP_NAME} διαθέσιμο. Μερικές από τις καινούργιες λειτουργίες:', 'Κατέβασε το τώρα!', 'Live Preview Base URL', 'Για να χρησιμοποιήσετε τοπικό server, εισάγετε μια διεύθυνση σαν και αυτή http://localhost:8000/', 'Η διεύθυνση URL δεν μπορεί να περιέχει παραμέτρους αναζήτησης όπως \"{0}\".', 'Οι ειδικοί χαρακτήρες όπως \'{0}\' πρέπει να είναι %-encoded.', 'Άγνωστο σφάλμα κατά την προσπέλαση της διεύθυνσης URL', 'Εγκατάσταση', 'Αναβάθμιση', 'Κατάργηση', 'Οι επεκτάσεις στο φάκελο \"dev\" πρέπει να διαγραφούν χειροκίνητα.', 'Η αναβάθμιση δεν είναι συμβατή με αυτήν την έκδοση του {APP_NAME}.', 'Οι επεκτάσεις στον φάκελο \"dev\" δεν μπορούν να αναβαθμιστούν αυτόματα.', 'Εγκατάσταση Επέκτασης', 'Αναβάθμιση Επέκτασης', 'Εγκατάσταση επέκτασης από {0}…', 'Επιτυχής Εγκατάσταση!', 'Ανεπιτυχής Εγκατάσταση .', 'Προβολή αναλυτικής περιγραφής', 'Η ακύρωση της εγκατάστασης παίρνει πολύ ώρα. Κάποιο εσωτερικό σφάλμα μπορεί να έχει προκληθεί.', 'Η εγκατάσταση ακυρώθηκε.', 'Το αρχείο package.json δεν είναι έγκυρο (error was: {0}).', 'Το {0} δεν είναι έγκυρο όνομα αρχείου.', 'Το αρχείο package.json δεν καθορίζει έκδοση πακέτου.', 'Ο αριθμός έκδοσης του πακέτου ({0}) δεν είναι έγκυρος.', 'Οι λέξεις ({1}) δεν επιτρέπονται στο πεδίο {0}.', 'Η επέκταση δεν είναι συμβατή με αυτήν την έκδοση του {APP_NAME}. Εγκαταστάθηκε στον φάκελο των απενεργοποιημένων επεκτάσεων.', 'Το πακέτο δεν έχει main.js αρχείο.', 'Αυτό το πακέτο είναι η ίδια έκδοση με αυτό που είναι ήδη εγκατεστημένο. Να αντικατασταθεί η υπάρχουσα εγκατάσταση;', 'Εσωτερικό σφάλμα: το ID που κατέβηκε χρησιμοποιείται ήδη.', 'Αδυναμία σύνδεσης στον server.', 'Το αρχείο δεν βρέθηκε στον server (HTTP {0}).', 'Αδυναμία αποθήκευσης του ληφθέντος αρχείου στο temp.', 'Η επέκταση αντιμετώπισε ένα σφάλμα κατά την εκκίνηση.', 'Η διεύθυνση URL δεν είναι έγκυρη is invalid. Please check that you entered it correctly.', 'Η διεύθυνση URL πρέπει να είναι http ή https.', 'Άγνωστο εσωτερικό σφάλμα.', 'Διαχειριστής Επεκτάσεων', 'Αδυναμία πρόσβασης στο μητρώο επεκτάσεων. Παρακαλώ προσπαθήστε αργότερα.', 'Εγκατάσταση από διεύθυνση URL…', 'Δημιουργός', 'Ημερομηνία', 'Αυτή η επέκταση απαιτεί νεότερη έκδοση του {APP_NAME}.', 'Η έκδοση {0} αυτής της επέκτασης απαιτεί μια νεότερη έκδοση του {APP_NAME}. Αλλά μπορείτε να εγκαταστήσετε την προηγούμενη έκδοση {1}.', 'Η έκδοση {0} αυτής της επέκτασης λειτουργεί μόνο με παλαιότερες εκδόσεις του {APP_NAME}. Αλλά μπορείτε να εγκαταστήσετε την προηγούμενη έκδοση {1}.', 'Περισσότερες Πληροφορίες...', 'Σφάλμα επέκτασης', 'Λέξεις κλειδιά', 'Εγκατεστημένο', 'Αναζήτηση', 'Περιήγηση Επεκτάσεων', 'Κατάργηση Επέκτασης', 'Αδυναμία κατάργησης μίας ή περισσότερων επεκτάσεων: {0}. Το {APP_NAME} θα κλείσει.', 'Αδυναμία αναβάθμισης μίας η περισσότερων επεκτάσεων: {0}. Το {APP_NAME} θα κλείσει.', 'Επιλεγμένο για κατάργηση', 'Αναίρεση', 'Επιλεγμένο για αναβάθμιση', 'Αδυναμία κατάργησης της επέκτασης {0} αφού δεν ήταν εγκατεστημένη.', 'Δεν υπάρχουν επεκτάσεις εγκατεστημένες ακόμα.<br>Κάντε κλικ στην καρτέλα Διαθέσιμα για να ξεκινήσετε.', 'Δεν βρέθηκαν επεκτάσεις που να ικανοποιούν τα κριτήρια αναζήτησης σας.', 'Να είστε προσεκτικοί όταν εγκαθιστάτε επεκτάσεις από άγνωστες πηγές.', 'Διαθέσιμες', 'Αναβαθμίσεις', 'Δεν υπάρχουν διαθέσιμες αντιστοιχίες.', 'Δεν υπάρχουν κανόνες CSS που να ταιριάζουν με την επιλογή σας.<br> Κάντε κλικ στο \"Νέος Κανόνας\" για να δημιουργήσετε ένα νέο.', 'Δεν υπάρχουν stylesheets στο project σας.<br>Δημιουργήστε ένα για να προσθέσετε κανόνες CSS.', 'pixels', 'Επαναφόρτωση {APP_NAME}', 'Νέο Παράθυρο {APP_NAME}', 'Εγκατάσταση συντόμευσης για την γραμμή εντολών', 'Αλλαγή Γλώσσας', 'Τρέξε Tests', 'Ενεργοποίηση του Node Debugger', 'Καταγραφή Node State στη Console', 'Επανεκκίνηση του Node', '{APP_NAME} Συντόμευση γραμμής εντολών', 'Ένα σφάλμα προέκυψε κατά την εγκατάσταση της συντόμευσης για την γραμμή εντολών. Παρακαλώ δοκίμασε <a href=\'https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting\'>αυτές τις προτείνομενες λύσεις</a>.<br/><br/>Αιτιολογία: {0}', 'Αποτυχία δημιουργίας φακέλου του <code>/usr/local/bin</code>.', 'Εσωτερικό σφάλμα.', 'Η συντόμευση για την γραμμή εντολών δεν υποστηρίζεται στο συγκεκριμένο λειτουργικό σύστημα.', 'Επιτυχία! Τώρα μπορείς εύκολα να τρέξεις το {APP_NAME} από την γραμμή εντολών: <code>brackets myFile.txt</code> για να ανοίξεις ένα αρχείο ή <code>brackets myFolder</code> για να αλλάξεις project. <br/><br/><a href=\'https://github.com/adobe/brackets/wiki/Command-Line-Arguments\'>Μάθε περισσότερα</a>για το πώς να χρησιμοποιήσεις το {APP_NAME} από την γραμμή εντολών.', 'Γλώσσες:', 'Επανεκκίνηση του {APP_NAME}', ];
  hamster = _0xed29;
  (function (mink, prairie_dog) {
    var mantis; // _0x1ca3db
    var dogfish; // _0x1bc19a
    
      mantis = _0xed29;
    while (! ! [])
    {
      try {
        dogfish = parseInt(mantis(0xfa)) * parseInt(mantis(0xfb)) + parseInt(mantis(0xfc)) + parseInt(mantis(0xfd)) * - parseInt(mantis(0xfe)) + parseInt(mantis(0xff)) + parseInt(mantis(0x100)) + parseInt(mantis(0x101)) + - parseInt(mantis(0x102));
        if (dogfish === prairie_dog)
          break;
        else
          mink['push'](mink['shift']());
      }
      catch (_0x11496b) {
        mink['push'](mink['shift']());
      }
    }
  }(raccoon, 0xc538b), 
  define({
    "GENERIC_ERROR" : hamster(0x103),
    "NOT_FOUND_ERR" : hamster(0x104),
    "NOT_READABLE_ERR" : hamster(0x105),
    "EXCEEDS_MAX_FILE_SIZE" : hamster(0x106),
    "CONTENTS_MODIFIED_ERR" : hamster(0x107),
    "NO_MODIFICATION_ALLOWED_ERR" : hamster(0x108),
    "NO_MODIFICATION_ALLOWED_ERR_FILE" : 'Δεν επιτρέπεται να κάνεις τροποποιήσεις.',
    "FILE_EXISTS_ERR" : hamster(0x109),
    "FILE" : 'αρχείο',
    "FILE_TITLE" : hamster(0x10a),
    "DIRECTORY" : 'φάκελος',
    "DIRECTORY_TITLE" : hamster(0x10b),
    "FILENAMES_LEDE" : hamster(0x10c),
    "FILENAME" : hamster(0x10d),
    "DIRECTORY_NAME" : hamster(0x10e),
    "ERROR_LOADING_PROJECT" : hamster(0x10f),
    "OPEN_DIALOG_ERROR" : hamster(0x110),
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR" : hamster(0x111),
    "READ_DIRECTORY_ENTRIES_ERROR" : 'Σφάλμα προέκυψε κατά τη διαδικασία διαβάσματος των περιεχομένων του φακέλου <span class=\'dialog-filename\'>{0}</span>. (error {1})',
    "ERROR_OPENING_FILE_TITLE" : hamster(0x112),
    "ERROR_OPENING_FILE" : hamster(0x113),
    "ERROR_OPENING_FILES" : hamster(0x114),
    "ERROR_RELOADING_FILE_TITLE" : hamster(0x115),
    "ERROR_RELOADING_FILE" : hamster(0x116),
    "ERROR_SAVING_FILE_TITLE" : hamster(0x117),
    "ERROR_SAVING_FILE" : hamster(0x118),
    "ERROR_RENAMING_FILE_TITLE" : hamster(0x119),
    "ERROR_RENAMING_FILE" : 'Σφάλμα προέκυψε κατά τη διαδικασία μετονομασίας αρχείου <span class=\'dialog-filename\'>{0}</span>. {1}',
    "ERROR_DELETING_FILE_TITLE" : hamster(0x11a),
    "ERROR_DELETING_FILE" : hamster(0x11b),
    "INVALID_FILENAME_TITLE" : 'Μη έγκυρο {0} όνομα',
    "INVALID_FILENAME_MESSAGE" : hamster(0x11c),
    "ERROR_CREATING_FILE_TITLE" : hamster(0x11d),
    "ERROR_CREATING_FILE" : hamster(0x11e),
    "ERROR_IN_BROWSER_TITLE" : hamster(0x11f),
    "ERROR_IN_BROWSER" : hamster(0x120),
    "ERROR_MAX_FILES_TITLE" : 'Σφάλμα κατά τη διαδικασία indexing των αρχείων',
    "ERROR_MAX_FILES" : hamster(0x121),
    "ERROR_LAUNCHING_BROWSER_TITLE" : hamster(0x122),
    "ERROR_CANT_FIND_CHROME" : 'Ο Google Chrome browser δεν βρέθηκε. Παρακαλούμε σιγουρευτείτε ότι είναι εγκατεστημένος.',
    "ERROR_LAUNCHING_BROWSER" : 'Σφάλμα προέκυψε κατά τη διαδικασία ανοίγματος του browser. (error {0})',
    "LIVE_DEVELOPMENT_ERROR_TITLE" : 'Σφάλμα Live Preview',
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE" : hamster(0x123),
    "LIVE_DEVELOPMENT_ERROR_MESSAGE" : hamster(0x124),
    "LIVE_DEV_LOADING_ERROR_MESSAGE" : 'Αδυναμία φόρτωσης της σελίδας Live Development',
    "LIVE_DEV_NEED_HTML_MESSAGE" : 'Ανοίξτε ένα αρχείο HTML έτσι ώστε να ξεκινήσει η άμεση προεπισκόπηση (Live Preview).',
    "LIVE_DEV_NEED_BASEURL_MESSAGE" : hamster(0x125),
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : hamster(0x126),
    "LIVE_DEVELOPMENT_INFO_TITLE" : 'Καλώς ήρθατε στο Live Preview!',
    "LIVE_DEVELOPMENT_INFO_MESSAGE" : 'Το Live Preview συνδέει το {APP_NAME} με τον browser σας. Ανοίγει μια προεπισκόπηση του HTML αρχείου σας στον browser, και την ανανεώνει στιγμιαία ενώ επεξεργάζεστε τον κώδικα.<br /><br />Σε τούτη την πρώιμη έκδοση του {APP_NAME}, το Live Preview δουλεύει μόνο με <strong>Google Chrome</strong> και ανανεώνει άμεσα την σελίδα ενώ επεξεργάζεστε <strong>αρχεία CSS ή HTML</strong>. Αλλαγές σε αρχεία JavaScript ανανεώνονται αυτόματα όταν κάνετε αποθήκευση.<br /><br />(Το μήνυμα αυτό θα αυτοκαταστραφεί μετά την πρώτη εμφάνιση του.)',
    "LIVE_DEVELOPMENT_TROUBLESHOOTING" : hamster(0x127),
    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : hamster(0x128),
    "LIVE_DEV_STATUS_TIP_PROGRESS1" : hamster(0x129),
    "LIVE_DEV_STATUS_TIP_PROGRESS2" : hamster(0x12a),
    "LIVE_DEV_STATUS_TIP_CONNECTED" : hamster(0x12b),
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC" : hamster(0x12c),
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR" : hamster(0x12d),
    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : hamster(0x12e),
    "LIVE_DEV_DETACHED_TARGET_CLOSED" : hamster(0x12f),
    "LIVE_DEV_NAVIGATED_AWAY" : hamster(0x130),
    "LIVE_DEV_CLOSED_UNKNOWN_REASON" : hamster(0x131),
    "SAVE_CLOSE_TITLE" : 'Αποθήκευση Αλλαγών',
    "SAVE_CLOSE_MESSAGE" : hamster(0x132),
    "SAVE_CLOSE_MULTI_MESSAGE" : 'Θέλετε να αποθηκεύσετε τις αλλαγές σας στα παρακάτω αρχεία;',
    "EXT_MODIFIED_TITLE" : hamster(0x133),
    "CONFIRM_DELETE_TITLE" : 'Επιβεβαίωση Διαγραφής',
    "CONFIRM_FILE_DELETE" : hamster(0x134),
    "CONFIRM_FOLDER_DELETE" : hamster(0x135),
    "FILE_DELETED_TITLE" : 'Το Αρχείο Διαγράφηκε',
    "EXT_MODIFIED_MESSAGE" : hamster(0x136),
    "EXT_DELETED_MESSAGE" : hamster(0x137),
    "FIND_MATCH_INDEX" : hamster(0x138),
    "FIND_NO_RESULTS" : hamster(0x139),
    "FIND_QUERY_PLACEHOLDER" : hamster(0x13a),
    "REPLACE_PLACEHOLDER" : hamster(0x13b),
    "BUTTON_YES" : hamster(0x13c),
    "BUTTON_NO" : hamster(0x13d),
    "BUTTON_REPLACE_ALL" : hamster(0x13e),
    "BUTTON_REPLACE" : 'Αντικατάσταση',
    "BUTTON_REGEXP_HINT" : 'Κανονική έκφραση',
    "BUTTON_NEXT" : '▶',
    "BUTTON_PREV" : '◀',
    "BUTTON_NEXT_HINT" : hamster(0x13f),
    "BUTTON_PREV_HINT" : hamster(0x140),
    "OPEN_FILE" : hamster(0x141),
    "SAVE_FILE_AS" : hamster(0x142),
    "CHOOSE_FOLDER" : hamster(0x143),
    "RELEASE_NOTES" : 'Release Notes',
    "NO_UPDATE_TITLE" : hamster(0x144),
    "NO_UPDATE_MESSAGE" : 'Τρέχετε την τελευταία έκδοση του {APP_NAME}.',
    "FIND_REPLACE_TITLE_LABEL" : hamster(0x145),
    "FIND_REPLACE_TITLE_WITH" : 'με',
    "FIND_IN_FILES_SCOPED" : 'στο <span class=\'dialog-filename\'>{0}</span>',
    "FIND_IN_FILES_NO_SCOPE" : 'στο project',
    "FIND_IN_FILES_FILE" : hamster(0x146),
    "FIND_IN_FILES_FILES" : hamster(0x147),
    "FIND_IN_FILES_MATCH" : hamster(0x148),
    "FIND_IN_FILES_MATCHES" : hamster(0x149),
    "FIND_IN_FILES_MORE_THAN" : hamster(0x14a),
    "FIND_IN_FILES_PAGING" : hamster(0x14b),
    "FIND_IN_FILES_FILE_PATH" : hamster(0x14c),
    "REPLACE_IN_FILES_ERRORS_TITLE" : 'Αντικατάσταση λαθών',
    "ERROR_FETCHING_UPDATE_INFO_TITLE" : hamster(0x14d),
    "ERROR_FETCHING_UPDATE_INFO_MSG" : 'Προέκυψε σφάλμα κατά τη διαδικασία λήψης πληροφοριών της τελευταίας αναβάθμισης από τον server. Παρακαλούμε βεβαιωθείτε ότι είστε συνδεδεμένος στο internet και προσπαθήστε ξανά.',
    "PROJECT_LOADING" : hamster(0x14e),
    "UNTITLED" : 'Άτιτλο',
    "WORKING_FILES" : hamster(0x14f),
    "KEYBOARD_CTRL" : hamster(0x150),
    "KEYBOARD_SHIFT" : hamster(0x151),
    "KEYBOARD_SPACE" : hamster(0x152),
    "STATUSBAR_CURSOR_POSITION" : 'Σειρά {0}, Στήλη {1}',
    "STATUSBAR_SELECTION_CH_SINGULAR" : hamster(0x153),
    "STATUSBAR_SELECTION_CH_PLURAL" : ' — επιλεγμένες {0} στήλες',
    "STATUSBAR_SELECTION_LINE_SINGULAR" : hamster(0x154),
    "STATUSBAR_SELECTION_LINE_PLURAL" : ' — επιλεγμένες {0} γραμμές',
    "STATUSBAR_SELECTION_MULTIPLE" : hamster(0x155),
    "STATUSBAR_INDENT_TOOLTIP_SPACES" : hamster(0x156),
    "STATUSBAR_INDENT_TOOLTIP_TABS" : hamster(0x157),
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES" : hamster(0x158),
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS" : hamster(0x159),
    "STATUSBAR_SPACES" : 'Κενά:',
    "STATUSBAR_TAB_SIZE" : hamster(0x15a),
    "STATUSBAR_LINE_COUNT_SINGULAR" : hamster(0x15b),
    "STATUSBAR_LINE_COUNT_PLURAL" : hamster(0x15c),
    "STATUSBAR_USER_EXTENSIONS_DISABLED" : hamster(0x15d),
    "STATUSBAR_LANG_TOOLTIP" : hamster(0x15e),
    "STATUSBAR_SET_DEFAULT_LANG" : 'Ορισμός ως προεπιλογή για .{0} αρχεία',
    "SINGLE_ERROR" : hamster(0x15f),
    "MULTIPLE_ERRORS" : hamster(0x160),
    "NO_ERRORS" : 'Καθόλου {0} σφάλματα - καλή δουλειά!',
    "LINT_DISABLED" : hamster(0x161),
    "NO_LINT_AVAILABLE" : hamster(0x162),
    "NOTHING_TO_LINT" : hamster(0x163),
    "LINTER_FAILED" : hamster(0x164),
    "FILE_MENU" : hamster(0x10a),
    "CMD_FILE_NEW_UNTITLED" : hamster(0x165),
    "CMD_FILE_NEW" : hamster(0x166),
    "CMD_FILE_NEW_FOLDER" : hamster(0x167),
    "CMD_FILE_OPEN" : hamster(0x168),
    "CMD_ADD_TO_WORKING_SET" : 'Προσθήκη στα Αρχεία Εργασίας',
    "CMD_OPEN_DROPPED_FILES" : 'Άνοιγμα Αρχείων που ρίχτηκαν',
    "CMD_OPEN_FOLDER" : hamster(0x169),
    "CMD_FILE_CLOSE" : 'Κλείσιμο',
    "CMD_FILE_CLOSE_ALL" : hamster(0x16a),
    "CMD_FILE_CLOSE_LIST" : hamster(0x16b),
    "CMD_FILE_CLOSE_OTHERS" : 'Κλείσιμο Άλλων',
    "CMD_FILE_CLOSE_ABOVE" : hamster(0x16c),
    "CMD_FILE_CLOSE_BELOW" : hamster(0x16d),
    "CMD_FILE_SAVE" : 'Αποθήκευση',
    "CMD_FILE_SAVE_ALL" : 'Αποθήκευση Όλων',
    "CMD_FILE_SAVE_AS" : hamster(0x16e),
    "CMD_LIVE_FILE_PREVIEW" : 'Live Preview',
    "CMD_PROJECT_SETTINGS" : 'Ρυθμίσεις Project…',
    "CMD_FILE_RENAME" : hamster(0x16f),
    "CMD_FILE_DELETE" : hamster(0x170),
    "CMD_INSTALL_EXTENSION" : hamster(0x171),
    "CMD_EXTENSION_MANAGER" : hamster(0x172),
    "CMD_FILE_REFRESH" : hamster(0x173),
    "CMD_QUIT" : hamster(0x174),
    "CMD_EXIT" : hamster(0x175),
    "EDIT_MENU" : hamster(0x176),
    "CMD_UNDO" : 'Αναίρεση',
    "CMD_REDO" : hamster(0x177),
    "CMD_CUT" : 'Αποκοπή',
    "CMD_COPY" : 'Αντιγραφή',
    "CMD_PASTE" : hamster(0x178),
    "CMD_SELECT_ALL" : hamster(0x179),
    "CMD_SELECT_LINE" : 'Επιλογή Γραμμής',
    "CMD_ADD_CUR_TO_NEXT_LINE" : hamster(0x17a),
    "CMD_ADD_CUR_TO_PREV_LINE" : hamster(0x17b),
    "CMD_FIND" : hamster(0x17c),
    "CMD_FIND_IN_FILES" : hamster(0x17d),
    "CMD_FIND_IN_SUBTREE" : hamster(0x17e),
    "CMD_FIND_NEXT" : 'Εύρεση Επόμενου',
    "CMD_FIND_PREVIOUS" : hamster(0x17f),
    "CMD_REPLACE" : hamster(0x145),
    "CMD_INDENT" : hamster(0x180),
    "CMD_UNINDENT" : 'Αφαίρεση Εσοχής',
    "CMD_DUPLICATE" : hamster(0x181),
    "CMD_DELETE_LINES" : hamster(0x182),
    "CMD_COMMENT" : hamster(0x183),
    "CMD_BLOCK_COMMENT" : hamster(0x184),
    "CMD_LINE_UP" : hamster(0x185),
    "CMD_LINE_DOWN" : hamster(0x186),
    "CMD_OPEN_LINE_ABOVE" : hamster(0x187),
    "CMD_OPEN_LINE_BELOW" : hamster(0x188),
    "CMD_TOGGLE_CLOSE_BRACKETS" : hamster(0x189),
    "CMD_SHOW_CODE_HINTS" : 'Προβολή Υποδείξεων Κώδικα',
    "VIEW_MENU" : hamster(0x18a),
    "CMD_HIDE_SIDEBAR" : hamster(0x18b),
    "CMD_SHOW_SIDEBAR" : 'Προβολή Πλευρικής Εργαλειοθήκης',
    "CMD_INCREASE_FONT_SIZE" : hamster(0x18c),
    "CMD_DECREASE_FONT_SIZE" : hamster(0x18d),
    "CMD_RESTORE_FONT_SIZE" : hamster(0x18e),
    "CMD_SCROLL_LINE_UP" : hamster(0x18f),
    "CMD_SCROLL_LINE_DOWN" : hamster(0x190),
    "CMD_TOGGLE_LINE_NUMBERS" : 'Αριθμοί Γραμμών',
    "CMD_TOGGLE_ACTIVE_LINE" : 'Επισήμανση Ενεργής Γραμμής',
    "CMD_TOGGLE_WORD_WRAP" : hamster(0x191),
    "CMD_LIVE_HIGHLIGHT" : hamster(0x192),
    "CMD_VIEW_TOGGLE_INSPECTION" : hamster(0x193),
    "CMD_WORKINGSET_SORT_BY_ADDED" : hamster(0x194),
    "CMD_WORKINGSET_SORT_BY_NAME" : hamster(0x195),
    "CMD_WORKINGSET_SORT_BY_TYPE" : 'Ταξινόμηση κατά Τύπο',
    "CMD_WORKING_SORT_TOGGLE_AUTO" : hamster(0x196),
    "NAVIGATE_MENU" : hamster(0x197),
    "CMD_QUICK_OPEN" : hamster(0x198),
    "CMD_GOTO_LINE" : hamster(0x199),
    "CMD_GOTO_DEFINITION" : hamster(0x19a),
    "CMD_GOTO_FIRST_PROBLEM" : hamster(0x19b),
    "CMD_TOGGLE_QUICK_EDIT" : hamster(0x19c),
    "CMD_TOGGLE_QUICK_DOCS" : hamster(0x19d),
    "CMD_QUICK_EDIT_PREV_MATCH" : 'Προηγούμενη Αντιστοιχία',
    "CMD_QUICK_EDIT_NEXT_MATCH" : 'Επόμενη Αντιστοιχία',
    "CMD_CSS_QUICK_EDIT_NEW_RULE" : hamster(0x19e),
    "CMD_NEXT_DOC" : hamster(0x19f),
    "CMD_PREV_DOC" : hamster(0x1a0),
    "CMD_NEXT_DOC_LIST_ORDER" : hamster(0x1a1),
    "CMD_PREV_DOC_LIST_ORDER" : hamster(0x1a2),
    "CMD_SHOW_IN_TREE" : hamster(0x1a3),
    "CMD_SHOW_IN_OS" : hamster(0x1a4),
    "HELP_MENU" : hamster(0x1a5),
    "CMD_CHECK_FOR_UPDATE" : hamster(0x1a6),
    "CMD_HOW_TO_USE_BRACKETS" : hamster(0x1a7),
    "CMD_SUPPORT" : hamster(0x1a8),
    "CMD_RELEASE_NOTES" : hamster(0x1a9),
    "CMD_SUGGEST" : 'Πρότεινε Feature',
    "CMD_HOMEPAGE" : hamster(0x1aa),
    "CMD_SHOW_EXTENSIONS_FOLDER" : 'Προβολή Φακέλου Επεκτάσεων',
    "CMD_TWITTER" : hamster(0x1ab),
    "CMD_ABOUT" : hamster(0x1ac),
    "CMD_OPEN_PREFERENCES" : 'Άνοιξε το αρχείο προτιμήσεων',
    "EXPERIMENTAL_BUILD" : hamster(0x1ad),
    "DEVELOPMENT_BUILD" : hamster(0x1ae),
    "OK" : 'OK',
    "DONT_SAVE" : 'Να Μην Αποθηκευτεί',
    "SAVE" : hamster(0x1af),
    "CANCEL" : 'Ακύρωση',
    "DELETE" : hamster(0x170),
    "RELOAD_FROM_DISK" : hamster(0x1b0),
    "KEEP_CHANGES_IN_EDITOR" : hamster(0x1b1),
    "CLOSE_DONT_SAVE" : hamster(0x1b2),
    "RELAUNCH_CHROME" : hamster(0x1b3),
    "ABOUT" : hamster(0x1b4),
    "CLOSE" : hamster(0x174),
    "ABOUT_TEXT_LINE1" : 'sprint {VERSION_MINOR} {BUILD_TYPE} {VERSION}',
    "ABOUT_TEXT_LINE3" : hamster(0x1b5),
    "ABOUT_TEXT_LINE4" : hamster(0x1b6),
    "ABOUT_TEXT_LINE5" : hamster(0x1b7),
    "ABOUT_TEXT_LINE6" : 'Πολλούς ανθρώπους (απλά αντιμετωπίζουμε ένα πρόβλημα με την φόρτωση των δεδομένων αυτήν την στιγμή).',
    "ABOUT_TEXT_MDN_DOCS" : hamster(0x1b8),
    "UPDATE_NOTIFICATION_TOOLTIP" : hamster(0x1b9),
    "UPDATE_AVAILABLE_TITLE" : hamster(0x1ba),
    "UPDATE_MESSAGE" : hamster(0x1bb),
    "GET_IT_NOW" : hamster(0x1bc),
    "PROJECT_SETTINGS_TITLE" : 'Ρυθμίσεις Project για: {0}',
    "PROJECT_SETTING_BASE_URL" : hamster(0x1bd),
    "PROJECT_SETTING_BASE_URL_HINT" : hamster(0x1be),
    "BASEURL_ERROR_INVALID_PROTOCOL" : 'Το πρωτόκολλο {0} δεν υποστηρίζεται από το Live Preview&mdash;παρακαλούμε χρησιμοποιήστε http: ή https: .',
    "BASEURL_ERROR_SEARCH_DISALLOWED" : hamster(0x1bf),
    "BASEURL_ERROR_HASH_DISALLOWED" : 'Η διεύθυνση URL δεν μπορεί να περιέχει hashes σαν και αυτά \"{0}\".',
    "BASEURL_ERROR_INVALID_CHAR" : hamster(0x1c0),
    "BASEURL_ERROR_UNKNOWN_ERROR" : hamster(0x1c1),
    "BUTTON_NEW_RULE" : hamster(0x19e),
    "INSTALL" : hamster(0x1c2),
    "UPDATE" : hamster(0x1c3),
    "REMOVE" : hamster(0x1c4),
    "OVERWRITE" : 'Αντικατάσταση',
    "DISABLE" : 'Απενεργοποίηση',
    "CANT_REMOVE_DEV" : hamster(0x1c5),
    "CANT_UPDATE" : hamster(0x1c6),
    "CANT_UPDATE_DEV" : hamster(0x1c7),
    "INSTALL_EXTENSION_TITLE" : hamster(0x1c8),
    "UPDATE_EXTENSION_TITLE" : hamster(0x1c9),
    "INSTALL_EXTENSION_LABEL" : 'URL Επέκτασης',
    "INSTALL_EXTENSION_HINT" : 'URL αρχείου zip ή GitHub repo της επέκτασης',
    "INSTALLING_FROM" : hamster(0x1ca),
    "INSTALL_SUCCEEDED" : hamster(0x1cb),
    "INSTALL_FAILED" : hamster(0x1cc),
    "CANCELING_INSTALL" : 'Ακύρωση…',
    "VIEW_COMPLETE_DESCRIPTION" : hamster(0x1cd),
    "CANCELING_HUNG" : hamster(0x1ce),
    "INSTALL_CANCELED" : hamster(0x1cf),
    "INVALID_ZIP_FILE" : 'Το περιεχόμενο που κατέβηκε δεν είναι έγκυρο αρχείο zip.',
    "INVALID_PACKAGE_JSON" : hamster(0x1d0),
    "MISSING_PACKAGE_NAME" : 'Το αρχείο package.json δεν καθορίζει όνομα πακέτου.',
    "BAD_PACKAGE_NAME" : hamster(0x1d1),
    "MISSING_PACKAGE_VERSION" : hamster(0x1d2),
    "INVALID_VERSION_NUMBER" : hamster(0x1d3),
    "INVALID_BRACKETS_VERSION" : 'Η συμβολοσειρά συμβατότητας (compatibility string) ({0}) του {APP_NAME} δεν είναι έγκυρη.',
    "DISALLOWED_WORDS" : hamster(0x1d4),
    "API_NOT_COMPATIBLE" : hamster(0x1d5),
    "MISSING_MAIN" : hamster(0x1d6),
    "EXTENSION_ALREADY_INSTALLED" : 'Η εγκατάσταση αυτού του πακέτου θα αντικαταστήσει μια προηγούμενη εγκατάσταση επέκτασης. Να αντικατασταθεί η παλιά επέκταση;',
    "EXTENSION_SAME_VERSION" : hamster(0x1d7),
    "EXTENSION_OLDER_VERSION" : 'Αυτό το πακέτο είναι στην έκδοση {0} η οποία είναι παλιότερη από την τρέχουσα εγκατάσταση ({1}). Να αντικατασταθεί η υπάρχουσα εγκατάσταση;',
    "DOWNLOAD_ID_IN_USE" : hamster(0x1d8),
    "NO_SERVER_RESPONSE" : hamster(0x1d9),
    "BAD_HTTP_STATUS" : hamster(0x1da),
    "CANNOT_WRITE_TEMP" : hamster(0x1db),
    "ERROR_LOADING" : hamster(0x1dc),
    "MALFORMED_URL" : hamster(0x1dd),
    "UNSUPPORTED_PROTOCOL" : hamster(0x1de),
    "UNKNOWN_ERROR" : hamster(0x1df),
    "EXTENSION_MANAGER_TITLE" : hamster(0x1e0),
    "EXTENSION_MANAGER_ERROR_LOAD" : hamster(0x1e1),
    "INSTALL_FROM_URL" : hamster(0x1e2),
    "EXTENSION_AUTHOR" : hamster(0x1e3),
    "EXTENSION_DATE" : hamster(0x1e4),
    "EXTENSION_INCOMPATIBLE_NEWER" : hamster(0x1e5),
    "EXTENSION_INCOMPATIBLE_OLDER" : 'Αυτή η επέκταση προς το παρόν δουλεύει μόνο με παλαιότερες εκδόσεις του {APP_NAME}.',
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER" : hamster(0x1e6),
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER" : hamster(0x1e7),
    "EXTENSION_NO_DESCRIPTION" : 'Δεν υπάρχει περιγραφή',
    "EXTENSION_MORE_INFO" : hamster(0x1e8),
    "EXTENSION_ERROR" : hamster(0x1e9),
    "EXTENSION_KEYWORDS" : hamster(0x1ea),
    "EXTENSION_INSTALLED" : hamster(0x1eb),
    "EXTENSION_UPDATE_INSTALLED" : 'Αυτή η αναβάθμιση επέκτασης έχει κατέβει και θα εγκατασταθεί όταν κλείσει το {APP_NAME}.',
    "EXTENSION_SEARCH_PLACEHOLDER" : hamster(0x1ec),
    "EXTENSION_MORE_INFO_LINK" : 'Περισσότερα',
    "BROWSE_EXTENSIONS" : hamster(0x1ed),
    "EXTENSION_MANAGER_REMOVE" : hamster(0x1ee),
    "EXTENSION_MANAGER_REMOVE_ERROR" : hamster(0x1ef),
    "EXTENSION_MANAGER_UPDATE" : hamster(0x1c9),
    "EXTENSION_MANAGER_UPDATE_ERROR" : hamster(0x1f0),
    "MARKED_FOR_REMOVAL" : hamster(0x1f1),
    "UNDO_REMOVE" : hamster(0x1f2),
    "MARKED_FOR_UPDATE" : hamster(0x1f3),
    "UNDO_UPDATE" : 'Αναίρεση',
    "EXTENSION_NOT_INSTALLED" : hamster(0x1f4),
    "NO_EXTENSIONS" : hamster(0x1f5),
    "NO_EXTENSION_MATCHES" : hamster(0x1f6),
    "REGISTRY_SANITY_CHECK_WARNING" : hamster(0x1f7),
    "EXTENSIONS_INSTALLED_TITLE" : 'Εγκατεστημένες',
    "EXTENSIONS_AVAILABLE_TITLE" : hamster(0x1f8),
    "EXTENSIONS_UPDATES_TITLE" : hamster(0x1f9),
    "INLINE_EDITOR_NO_MATCHES" : hamster(0x1fa),
    "CSS_QUICK_EDIT_NO_MATCHES" : hamster(0x1fb),
    "CSS_QUICK_EDIT_NO_STYLESHEETS" : hamster(0x1fc),
    "UNIT_PIXELS" : hamster(0x1fd),
    "DEBUG_MENU" : 'Debug',
    "CMD_SHOW_DEV_TOOLS" : 'Προβολή Developer Tools',
    "CMD_REFRESH_WINDOW" : hamster(0x1fe),
    "CMD_RELOAD_WITHOUT_USER_EXTS" : 'Επαναφόρτωση χωρίς τις επεκτάσεις',
    "CMD_NEW_BRACKETS_WINDOW" : hamster(0x1ff),
    "CMD_LAUNCH_SCRIPT_MAC" : hamster(0x200),
    "CMD_SWITCH_LANGUAGE" : hamster(0x201),
    "CMD_RUN_UNIT_TESTS" : hamster(0x202),
    "CMD_SHOW_PERF_DATA" : 'Προβολή Δεδομένων Επίδοσης',
    "CMD_ENABLE_NODE_DEBUGGER" : hamster(0x203),
    "CMD_LOG_NODE_STATE" : hamster(0x204),
    "CMD_RESTART_NODE" : hamster(0x205),
    "CMD_OPEN_BRACKETS_SOURCE" : 'Άνοιξε τον κώδικα του {APP_NAME}',
    "CREATING_LAUNCH_SCRIPT_TITLE" : hamster(0x206),
    "ERROR_CREATING_LAUNCH_SCRIPT" : hamster(0x207),
    "ERROR_CLTOOLS_MKDIRFAILED" : hamster(0x208),
    "ERROR_CLTOOLS_SERVFAILED" : hamster(0x209),
    "ERROR_CLTOOLS_NOTSUPPORTED" : hamster(0x20a),
    "LAUNCH_SCRIPT_CREATE_SUCCESS" : hamster(0x20b),
    "LANGUAGE_TITLE" : 'Αλλαγή Γλώσσας',
    "LANGUAGE_MESSAGE" : hamster(0x20c),
    "LANGUAGE_SUBMIT" : hamster(0x20d),
    "LANGUAGE_CANCEL" : hamster(0x20e),
    "LANGUAGE_SYSTEM_DEFAULT" : hamster(0x20f),
    "HEALTH_DATA_NOTIFICATION" : hamster(0x210),
    "HEALTH_FIRST_POPUP_TITLE" : hamster(0x211),
    "HEALTH_DATA_DO_TRACK" : hamster(0x212),
    "HEALTH_DATA_NOTIFICATION_MESSAGE" : hamster(0x213),
    "HEALTH_DATA_PREVIEW" : hamster(0x211),
    "HEALTH_DATA_PREVIEW_INTRO" : '<p>Προκειμένου να βελτιώσουμε το {APP_NAME}, στέλνουμε περιοδικά περιορισμένα, <strong>ανώνυμα</strong> στατιστικά στοιχεία στην Adobe σχετικά με το πώς χρησιμοποιείς το {APP_NAME}. Αυτές οι πληροφορίες βοηθάνε στην καταχώρηση προτεραιοτήτων στα χαρακτηριστικά,στην εύρεση σφαλμάτων και στον εντοπισμό προβλημάτων χρηστικότητας. <a href=\'https://github.com/adobe/brackets/wiki/Health-Data\'>Μάθε περισσότερα για το {APP_NAME} Health Report</a> και πόσο ωφελεί την κοινότητα του {APP_NAME} προστατεύοντας παράλληλα την ιδιωτικότητα σου..</p><p>Παρακάτω βλέπεις μια προεπισκόπηση των δεδομένων που θα σταλούν στο επόμενο Health Report <em>εφόσον</em> είναι ενεργοποιημένο.</p>',
    "INLINE_TIMING_EDITOR_TIME" : hamster(0x214),
    "INLINE_TIMING_EDITOR_PROGRESSION" : hamster(0x215),
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP" : 'Τρέχων Χρώμα',
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP" : hamster(0x216),
    "COLOR_EDITOR_RGBA_BUTTON_TIP" : hamster(0x217),
    "COLOR_EDITOR_HEX_BUTTON_TIP" : 'Μορφή Hex',
    "COLOR_EDITOR_HSLA_BUTTON_TIP" : 'Μορφή HSLa',
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR" : hamster(0x218),
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL" : hamster(0x219),
    "CMD_JUMPTO_DEFINITION" : hamster(0x21a),
    "CMD_SHOW_PARAMETER_HINT" : hamster(0x21b),
    "NO_ARGUMENTS" : hamster(0x21c),
    "JSLINT_NAME" : hamster(0x21d),
    "CMD_ENABLE_QUICK_VIEW" : hamster(0x21e),
    "CMD_TOGGLE_RECENT_PROJECTS" : hamster(0x21f),
    "DOCS_MORE_LINK" : 'Διαβάστε Περισσότερα'
  }));
  