  function chives(chinchilla, ibex) {
    return _0xf45a = function (boar, llama) {
      var capybara; // _0x350c59
      
          boar = boar - 0xac;
      capybara = raccoon[boar];
      return capybara;
    }, 
    chives(chinchilla, ibex);
  }
  var raccoon; // _0xf0be
  var hamster; // _0x221952
  
  raccoon = ['Soubor <span class=\'dialog-filename\'>{0}</span> ve složce <span class=\'dialog-path\'>{1}</span>', 'Ctrl/Cmd klik pro rozbalení/sbalení všeho', 'Indexování pro okamžité vyhledávání…', 'Nahradit chyby', 'Následující soubory nebyly změněny, protože se změnily po hledání nebo do nich nelze zapisovat.', 'Chyba při získávání informací o aktualizaci', 'Nelze získat aktualizace. Ujistěte se, že máte připojení k internetu a zkuste to znovu.', 'Nová řada vyloučených souborů…', 'Nevylučovat soubory', 'Upravit…', 'Upravit filtr', 'Vyloučit soubory a složky, které obsahují jakýkoliv z následujících řetězců / podřetězců nebo <a href=\'{0}\' title=\'{0}\'>vzorků</a>. Vložte každý řetězec na nový řádek.', 'Pojmenujte řadu vyloučených souborů (nepovinné)', 'a {0} více', 'Počítání souborů…', 'Povolit {0} z {1} souborů {2}', 'Povolit všechny {0} soubory {1}', 'Rychlá úprava není dostupná pro aktuální pozici kurzoru', 'Rychlá úprava CSS: umístěte kurzor do jména třídy', 'Rychlá úprava CSS: nekompletní class atribut', 'Rychlá úprava CSS: nekompletní id atribut', 'Rychlá úprava CSS: umístěte kurzor do elementu, třídy nebo id', 'Rychlá úprava CSS časování: neplatná syntaxe', 'Rychlá úprava JS: umístěte kurzor do jména funkce', 'Načítání…', 'Nový', 'Pracovní soubory', 'Vlevo', 'Vpravo', 'Vertikální rozdělení', 'Horizontální rozdělení', 'Rozdělit editor horizontálně nebo vertikálně', 'Nastavit pracovní plochu', 'Již otevřen', 'Soubor je již otevřen v jiném okně. {APP_NAME} bude brzy podporovat otevírání stejného souboru ve více oknech. Do té doby bude soubor zobrazen v již otevřeném okně.<br /><br />(Tuto zprávu uvidíte pouze jednou.)', 'Ctrl', 'Shift', 'Mezerník', 'Page Down', 'Home', 'End', 'Insert', 'Delete', 'Řádek {0}, Sloupec {1}', ' — Vybrán {0} sloupec', ' — Vybrány {0} sloupce', ' — Vybrán {0} řádek', ' — Vybrány {0} řádky', ' — {0} Vybráno', 'Přepnout odsazení na mezery', 'Přepnout odsazení na tabulátory', 'Změnit šířku tabulátoru', 'Mezery:', 'Řádky: {0}', 'Doplňky zakázány', 'INS', 'Klikněte pro přepnutí kurzoru mezi módem Insert (INS) a Overwrite (OVR)', '(výchozí)', 'Nastavit jako výchozí pro .{0} soubory', '{0} chyb', '1 {0} chyba', '{1} {0} chyby', 'Žádné chyby nenalezeny - dobrá práce!', 'Lintování je vypnuto', 'Žádný linter není dostupný pro {0}', 'Nic k lintování', '{0} - vypršel časový limit po uplynutí {1} ms', '{0} byl(a) ukončen(a) s chybou: {1}', 'Nový soubor', 'Nová složka', 'Zavřít', 'Zavřít vše', 'Zavřít seznam', 'Zavřít ostatní', 'Zavřít ostatní výše', 'Zavřít ostatní níže', 'Uložit vše', 'Experimentální živý náhled', 'Vynutit obnovení živého náhledu', 'Přejmenovat', 'Smazat', 'Instalovat doplňky…', 'Správce doplňků…', 'Konec', 'Úpravy', 'Zpět', 'Vložit', 'Vybrat vše', 'Vybrat řádek', 'Rozdělit výběr na řádky', 'Přidat kurzor na další řádek', 'Odsadit', 'Vrátit odsazení', 'Duplikovat', 'Smazat řádek', 'Řádkový komentář', 'Blokový komentář', 'Posunout řádek dolů', 'O řádek výše', 'O řádek níže', 'Uzavírat závorky', 'Zobrazit nápovědy kódu', 'Najít', 'Najít další', 'Najít předchozí', 'Najít vše a vybrat', 'Přeskočit a přidat další shodu do výběru', 'Najít v…', 'Nahradit v souborech', 'Nahradit v…', 'Skrýt boční menu', 'Zobrazit boční menu', 'Zobrazit/skrýt boční menu', 'Žádné rozptylování', 'Obnovit velikost písma', 'Posunout o řádek nahoru', 'Posunout o řádek dolů', 'Čísla řádků', 'Zalomit řádky', 'Živé zvýraznění', 'Lintovat soubory při uložení', 'Řadit podle jména', 'Řadit podle typu', 'Automatické řazení', 'Navigace', 'Rychle otevřít', 'Přejít na řádek', 'Přejít na definici', 'Rychlá úprava', 'Rychlá dokumentace', 'Předchozí shoda', 'Nový předpis', 'Další dokument', 'Předchozí dokument', 'Další dokument v seznamu', 'Předchozí dokument v seznamu', 'Zobrazit stromovou strukturu', 'Zobrazit v OS', 'Zkontrolovat aktualizace', 'Jak používat {APP_NAME}', 'Navrhněte funkci', 'Zapojte se', 'Zobrazit složku s doplňky', 'Hlášení o zdraví', 'Domovská stránka {APP_TITLE}', '{TWITTER_NAME} na Twitteru', 'O aplikaci {APP_TITLE}', 'Otevřít soubor s preferencemi', 'Otevřít uživatelské klávesové zkratky', 'experimentální sestavení', 'sestavení', 'vývojové sestavení', 'Načíst z disku', 'Ponechat změny v editoru', 'Zavřít (neukládat)', 'Vydání {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}', 'vytvořeno: ', 'Dokumentace a zdrojový kód na stránce <a href=\'https://github.com/adobe/brackets/\'>https://github.com/adobe/brackets/</a>.', 'Vytvořeno s ❤ a pomocí JavaScriptu těmito lidmi:', 'Mnoho lidí (ale momentálně máme problém s načítáním dat).', 'MDN Docs a MDN logo využívají licenci Creative Commons Attribution, <a href=\'{MDN_DOCS_LICENSE}\'>CC-BY-SA 2.5 Unported</a>.', 'Je dostupná nová verze {APP_NAME}! Klikněte zde pro více informací.', 'Nová verze {APP_NAME} je dostupná. Seznam některých vylepšení:', 'Stáhnout!', 'Nastavení projektu: {0}', 'URL Živého náhledu', '(nechte prázdné pro URL souboru)', '{0} protokol není podporován živým náhledem &mdash; prosím, použijte http: nebo https: .', 'URL nemůže obsahovat znaky jako \"{0}\".', 'Zvláštní znaky jako \'{0}\' musí být zakódovány %.', 'Aktuální motiv', 'Velikost písma', 'Rodina písma', 'Aktualizovat', 'Odstranit', 'Deaktivovat', 'Aktivovat', 'Doplněk ve složce \"dev\" musí být smazán manuálně.', 'Aktualizace není kompatibilní s touto verzí {APP_NAME}.', 'Aktualizovat doplněk', 'URL adresa doplňku', 'URL adresa zip archivu nebo GitHub repozitáře', 'Instalace doplňku z {0}…', 'Instalace byla úspěšná!', 'Rušení instalace…', 'Rušení instalace trvá dlouho. Mohlo dojít k interní chybě.', 'Instalace zrušena.', 'Zobrazit úplný popis', 'Zobrazit zkrácený popis', 'Stažený soubor není platný zip soubor.', 'Package.json balíček nespecifikuje jméno souboru.', '{0} je neplatné jméno balíčku.', 'Package.json balíček nespecifikuje verzi souboru.', 'Balíček verze ({0}) je neplatný.', 'Řetězec kompatibility {0} pro {APP_NAME} je neplatný.', 'Balíček neobsahuje soubor main.js.', 'Instalace tohoto balíčku přepíše již nainstalovaný doplněk. Chcete přepsat starý doplněk?', 'Tento balíček je verze {0}, která je starší než současně nainstalovaná verze ({1}). Chcete přepsat existující doplněk?', 'Soubor nebyl nalezen (HTTP {0}).', 'Nelze uložit do dočasných souborů.', 'URL adresa je neplatná. Ujistěte se, že jste adresu zadali správně.', 'Nelze získat přístup k registru doplňků. Prosím, zkuste to znovu později.', 'Přetáhněte .zip zde nebo', 'Pusťte .zip pro instalaci', 'Instalace/aktualizace byla zrušena kvůli následujících chyb:', 'Instalovat z URL…', 'Ověření…', 'Autor', 'Datum', 'Tento doplněk požaduje novější verzi {APP_NAME}.', 'Tento doplněk funguje pouze ve starší verzi {APP_NAME}.', 'Verze {0} tohoto doplňku vyžaduje novější verzi {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.', 'Verze {0} tohoto doplňku funguje pouze se starší verzí {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.', 'Chyba doplňku', 'Klíčová slova', 'Přeloženo do {0} jazyků, včetně vašeho', 'Přeloženo do {0} jazyků', 'Nainstalováno', 'Aktualizace doplňku byla stažena a bude nainstalována při ukončení aplikace {APP_NAME}.', 'Hledat', 'Více', 'Procházet doplňky', 'Odstranit doplněk', 'Nelze odstranit jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.', 'Nelze aktualizovat jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.', 'Deaktivovat doplněk', 'Nelze deaktivovat jeden nebo více doplňků: {0}. Aplikace {APP_NAME} se i přesto restartuje.', 'Označeno k odstranění', 'Označeno k aktualizaci', 'Označeno k deaktivaci', 'Změnit doplňky', 'K aktualizaci, odstranění nebo deaktivaci označených doplňků je třeba restartovat aplikaci {APP_NAME}. Budete vyzváni k uložení změn.', 'Odstranit doplňky a restartovat', 'Aktualizovat doplňky a restartovat', 'Deaktivovat doplňky a restartovat', 'Zpracování změn doplňku…', 'Žádný doplněk ještě nebyl nainstalován.<br>Klikněte na tlačítko Instalovat z URL pro zahájení instalace.', 'Žádný doplněk neodpovídá hledání.', 'POZNÁMKA: Tyto doplňky mohou pocházet od jiných autorů než {APP_NAME}. Buďte opatrní při instalaci doplňků z neznámých zdrojů.', 'Nainstalované', 'Dostupné', 'Aktualizace', 'Žádné dostupné shody.', 'Všechny shody jsou sbalené. Pro prohlédnutí shod rozbalte soubory zobrazené vpravo.', 'Neexistují žádné CSS předpisy odpovídající vašemu výběru.<br>Pro vytvoření předpisu klikněte na \"Nový předpis\".', 'Neexistují žádné soubory s kaskádovými styly ve vašem projektu.<br>Vytvořte nový soubor pro přidání CSS předpisů.', 'největší', 'Nástroje', 'Chyby', 'Zobrazit nástroje pro vývojáře', 'Nové okno {APP_NAME}', 'Nainstalovat zástupce do příkazové řádky', 'Změnit jazyk', 'Zobrazit údaje o výkonnosti', 'Povolit Node Debugger', 'Uložit stav Node do konzole', 'Restartovat Node', 'Zobrazit chyby ve stavovém řádku', 'Otevřít zdroj {APP_NAME}', 'Zástupce {APP_NAME} v příkazové řádce', 'Při instalaci zástupce do příkazové řádky se vyskytla chyba. Prosím vyzkoušejte řešení <a href=\'https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting\'>na této stránce</a>.<br/><br/>Důvod: {0}', 'Nelze odstranit existující symbolický odkaz na <code>/usr/local/bin/brackets</code>.', 'Nelze vytvořit složku <code>/usr/local/bin</code>.', 'Nelze vytvořit symbolický odkaz na <code>/usr/local/bin/brackets</code>.', 'V tomto operačním systému nelze vytvořit zástupce do příkazové řádky.', 'Hotovo! Nyní můžete jednoduše spustit {APP_NAME} z příkazové řádky: příkazem <code>brackets myFile.txt</code> otevřete soubor a příkazem <code>brackets myFolder</code> změníte projekt. <br/><br/><a href=\'https://github.com/adobe/brackets/wiki/Command-Line-Arguments\'>Na této stránce zjistíte více</a> o používání {APP_NAME} z příkazové řádky.', 'Prosím, vyberte jazyk ze seznamu:', 'Restartovat {APP_NAME}', 'Nastavení hlášení o zdraví', 'Hlášení o zdraví {APP_NAME}', 'Kvůli vylepšování {APP_NAME} odesíláme společnosti Adobe pravidelně omezené <strong>anonymní</strong> statistiky o používání {APP_NAME}. Tyto informace pomáhají upřednostnit některé funkce, předcházet chybám a všimnout si nedostatků v použitelnosti.<br><br>Vaše data si můžete prohlédnout nebo zakázat jejich sdílení výběrem <strong>Nápověda > Hlášení o zdraví</strong>.<br><br><a href=\'https://github.com/adobe/brackets/wiki/Health-Data\'>Zjistěte více ke hlášení o zdraví {APP_NAME}</a>', '<p>Kvůli vylepšování {APP_NAME} odesíláme společnosti Adobe pravidelně omezené <strong>anonymní</strong> statistiky o používání {APP_NAME}. Tyto informace pomáhají upřednostnit některé funkce, předcházet chybám a všimnout si nedostatků v použitelnosti. <a href=\'https://github.com/adobe/brackets/wiki/Health-Data\'>Zjistěte více ke hlášení o zdraví {APP_NAME}</a> a jak je pro komunitu {APP_NAME} prospěšné, zatímco je chráněno vaše soukromí.</p><p>Níže je náhled dat, která budou odeslána v příštím hlášení o zdraví, <em>pokud</em> je odesílání povoleno.</p>', 'Doba', '<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Posunout vybraný bod<br><kbd class=\'text\'>Shift</kbd> Posunout o deset jednotek<br><kbd class=\'text\'>Tab</kbd> Vyměnit body', '<kbd>↑</kbd><kbd>↓</kbd> Zvýšení nebo snížení kroků<br><kbd>←</kbd><kbd>→</kbd> \'Start\' nebo \'End\'', 'Stará hodnota <code>{0}</code> není platná, proto zobrazená funkce byla změněna na <code>{1}</code>. Dokument bude aktualizován při první úpravě.', 'Současná barva', 'Původní barva', 'RGBa formát', 'Hex formát', 'HSLa formát', '{0} (použito {1} krát)', 'Zobrazit nápovědu parametru', '<žádné parametry>', 'Inferenční problém JavaScript souboru', 'JSLint', 'Rychlý náhled', 'Nedávné projekty', 'Skrýt vše', 'Zobrazit vše', 'Skrýt aktuální', 'Zobrazit aktuální', 'false k odebrání \"Zavřít ostatní výše\" z kontextového menu pracovních souborů', 'false k odebrání \"Zavřít ostatní níže\" z kontextového menu pracovních souborů', 'false k odebrání \"Zavřít ostatní\" z kontextového menu pracovních souborů', 'Nastavit možnosti uzavírání značek', 'Pole značek, které by neměly být automaticky uzavírány', 'Zavřít, pokud je napsán > otevírací značky', 'Pole značek, do kterých je po jejich otevření vložen prázdný řádek', 'true k vygenerování záložek skrývajících kód vždy, když se změní úroveň odsazení', 'true k povolení skrývání kódu', 'true k zobrazení záložek skrývajících kód pouze pokud přejedete myší nad okrajem', 'Limity, kolik úrovní do hloubky platí Skrýt vše', 'true k zapamatování skrytých částí pokud zavřete a znovu otevřete soubor nebo projekt', 'true k povolení skrývání kódu při výběru textu v editoru', 'Povolit/zakázat nápovědy CSS/LESS/SCSS hodnot', 'Povolit/zakázat detaily o datových typech v nápovědách kódu u JavaScriptu', 'Povolit/zakázat nápovědy v preferencích', 'Povolit/zakázat nápovědy HTML entit', 'Povolit/zakázat nápovědy HTML značek', 'Povolit/zakázat funkci Drag & Drop', 'Povolit sledování hlášení o zdraví', 'Zvýraznit všechny výrazy shodující se s výrazem, na kterém je aktuálně kurzor (není nutný výběr výrazu)', 'true k vložení aktuálně vybrané nápovědy při tabulátoru', 'true k zamezení automatického zobrazení nápověd JS kódu, jestliže je napsaná .', 'true k povolení přiřazených výrazů', 'true k povolení bitových operátorů', 'true k povolení idiomů Google Closure', 'true pokud by globální proměnné CouchDB měly být předdefinované', 'true k povolení příkazů debuggeru', 'true pokud by globální proměnné prohlížeče užitečné při vývoji měly být předdefinované', 'true k povolení == a !=', 'true pokud by globální proměnné ES6 měly být předdefinované', 'Nastavit vlastní šířku tabulátoru', 'Maximální počet hlášených varování', 'true k povolení nevyužitých konstruktorů', 'true pokud by globální proměnné Node.js měly být předdefinované', 'true k zastavení na první chybě', 'true k povolení ++ a --', 'true k povolení . a [^...]. v RegExpu', 'true pokud by globální proměnné Rhino měly být předdefinované', 'true k povolení chybějících `use strict`', 'true pokud může být použito blokování (\'...Sync\') metod.', 'true k povolení neefektivního indexování', 'true k povolení TODO komentářů', 'true k povolení více než 1 proměnné ve funkci', 'Vlastní nastavení jazyků', 'Dodatečná mapování z přípony souboru na jméno jazyka', 'Pole linterů spouštěných nejdříve', 'true k povolení experimentálního živého náhledu', 'true ke spuštění poskytovatelů určených pouze v linting.prefer', 'Maximální počet současně zobrazených nápověd kódu', 'Vlastní nastavení cest', 'true k povolení rolování za konec dokumentu', 'false k zakázání všech nápověd kódu', 'Při výběru textu nechat zobrazený blikající kurzor', 'true ke zobrazení čísel řádků na okraji vlevo od kódu', 'Automaticky odsadit při vytvoření nového bloku', 'false k zamezení nahrazování tabulátorů mezerami', 'true k řazení složek nahoru ve stromu souborů projektu', 'Síťový port, který by zabudovaný server měl použít pro živý náhled', 'Počet zobrazených mezer místo tabulátoru', 'true k používání tabulátorů místo mezer', 'true k vygenerování hex barev velkými písmeny v Inline Color Editor', 'Seznam souborů, u kterých bylo zjištěno, že způsobují, že se Tern vymkne kontrole', 'Doba, po jejímž uplynutí Tern při snaze porozumět souborům vyprší', 'true ke zobrazení chyb ve stavovém řádku', 'true k povolení rychlého náhledu', 'true ke zobrazení náhledů obrázků pro chybějící přípony URL', 'Vybrat motiv {APP_NAME}', 'true k povolení vlastních posuvníků', 'Změnit písmo', 'Změnit velikost písma, např. 13px', 'true k povolení vyhledávání založeného na Node', 'true k povolení okamžitého vyhledávání', 'Pouze pro Mac: \"subpixel-antialiased\" k povolení sub-pixel vyhlazování nebo \"antialiased\" k vyhlazování v odstínech šedi', 'false k zamezení otevírání souboru s preferencemi v rozděleném editoru', 'false k otevření souboru s preferencemi v levém/horním panelu', 'true ke skrytí panelů po zavření posledního souboru z panelu pomocí tlačítka na hlavičce panelu', 'Změňte ke zobrazení tlačítek zavřít a rozdělit ve hlavičce.', '/*\n * Toto je soubor pouze ke čtení s preferencemi podporovanými\n * v {APP_NAME}.\n * Použijte tento soubor jako doporučení pro úpravu vašeho souboru s preferencemi\n * \"brackets.json\" otevřeném ve druhém panelu.\n * Pro více informací o úpravě preferencí\n * v {APP_NAME} se podívejte na webovou stránku https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */', 'true k povolení módu pouze s kódem a ke skrytí Všech dalších UI prvků v {APP_NAME}', '4369KMuLep', '69IwaQDe', '1bDuTrh', '887162xZefLj', '927607UTBUUp', '656309tyHLdK', '1194828MyvJQz', '1sOWbeM', '452413sfVhjq', '3819194QmijjF', '(chyba {0})', 'Soubor nenalezen.', 'Soubor nelze číst.', 'Cílová složka nemůže být změněna.', 'Oprávnění neumožní provádět změny.', 'Soubor byl změněn mimo aplikaci {APP_NAME}.', '{APP_NAME} v této chvíli podporuje pouze UTF-8 textové soubory.', 'Soubor již existuje.', 'souboru', 'složky', 'Složka', 'Názvy složek', 'název souboru', 'název složky', 'Došlo k chybě při zobrazování dialogu Otevřít soubor. (chyba {0})', 'Došlo k chybě při načítání adresáře <span class=\'dialog-filename\'>{0}</span>. (chyba {1})', 'Došlo k chybě při načítání obsahu složky <span class=\'dialog-filename\'>{0}</span>. (chyba {1})', 'Chyba při otevírání souboru', 'Došlo k chybě při otevírání souboru <span class=\'dialog-filename\'>{0}</span>. {1}', 'Došlo k chybě při otevírání následujících souborů:', 'Chyba při načítání změn z disku', 'Došlo k chybě při ukládání souboru <span class=\'dialog-filename\'>{0}</span>. {1}', 'Chyba při přejmenování {0}', 'Došlo k chybě při přejmenování {2} <span class=\'dialog-filename\'>{0}</span>. {1}', 'Došlo k chybě při mazání {2} <span class=\'dialog-filename\'>{0}</span>. {1}', 'Špatný {0}', '{0} nemohou obsahovat rezervovaná slova, končit tečkami (.) nebo obsahovat znaky: <code class=\'emphasized\'>{1}</code>', 'Soubor nebo složka se jménem <span class=\'dialog-filename\'>{0}</span> již existuje.', 'Chyba při vytváření {0}', 'Došlo k chybě při vytváření {0} <span class=\'dialog-filename\'>{1}</span>. {2}', 'Nelze otevřít složku ve chvíli, kdy se otevírají jiné soubory.', 'Chyba při čtení uživatelských klávesových zkratek', 'Soubor s nastavením klávesových zkratek není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát.', 'Váš soubor s klávesovými zkratkami není platný UTF-8 soubor a nemůže být otevřen', 'Nemůžete změnit klávesové zkratky následujícím příkazům: {0}', 'Nemůžete změnit tyto klávesové zkratky: {0}', 'Vytváříte více klávesových zkratek pro tyto příkazy: {0}', 'Tyto klávesové zkratky jsou neplatné: {0}', 'Vytváříte klávesovou zkratku pro neexistující příkaz: {0}', 'Soubor s preferencemi vašeho projektu neodpovídá validnímu JSON formátu. Tento soubor bude otevřen, abyste mohl formát opravit. K provedení změn bude nutné znovu načíst projekt.', 'Ouha! {APP_NAME} ještě neběží v prohlížeči.', 'Chyba při indexování souborů', 'Tento projekt obsahuje více než 30.000 souborů. Funkce zpracovávající více souborů mohou být zablokované nebo se mohou chovat jako kdyby byl projekt prázdný. <a href=\'https://github.com/adobe/brackets/wiki/Large-Projects\'>Čtěte více o práci s obřími projekty</a>.', 'Chyba při spouštění prohlížeče', 'Prohlížeč Google Chrome nebyl nalezen. Přesvědčte se, že je nainstalován', 'Došlo k chybě při spouštění prohlížeče. (chyba {0})', 'Živý náhled - chyba', 'Připojování k prohlížeči', 'Aby se mohl živý náhled připojit, je třeba restartovat Chrome s povolenou možností vzdálené ladění.<br /><br />Chcete restartovat Chrome a povolit vzdálené ladění?<br /><br />', 'Nelze načíst stránku s živým náhledem', 'Otevřete HTML soubor pro zobrazení v živém náhledu.', 'Chyba při spouštění HTTP serveru pro soubory živého náhledu. Prosím, zkuste to znovu.', 'Vítejte v živém náhledu!', 'Živý náhled připojí {APP_NAME} k vašemu prohlížeči. Spustí náhled HTML souboru, který se aktualizuje pokaždé, kdy editujete svůj kód.<br /><br />V této verzi {APP_NAME}, živý náhled funguje pouze v <strong>Google Chrome</strong> a aktualizuje změny v <strong>CSS souborech</strong>. Změny v HTML nebo JavaScript souborech jsou automaticky načteny, když soubor uložíte.<br /><br />(Tato zpráva se zobrazí pouze jednou.)', 'Živý náhled: Připojování…', 'Živý náhled: Spouštění…', 'Živý náhled (uložte soubor k obnovení)', 'Živý náhled (neaktualizováno kvůli chybě v syntaxi)', 'Živý náhled byl zrušen, protože byly otevřeny vývojářské nástroje prohlížeče', 'Živý náhled byl zrušen, protože dokument byl zavřen v prohlížeči', 'Živý náhled byl zrušen, protože prohlížeč přešel na stránku, která není součástí projektu', 'Živý náhled byl zrušen z neznámého důvodu ({0})', 'Uložit změny', 'Chcete uložit změny v následujících souborech?', 'Opravdu chcete smazat složku <span class=\'dialog-filename\'>{0}</span>?', 'Soubor smazán', '<span class=\'dialog-filename\'>{0}</span> byl změněn mimo {APP_NAME}, ale existují také neuložené změny v {APP_NAME}.<br /><br />Kterou verzi chcete zachovat?', '<span class=\'dialog-filename\'>{0}</span> byl smazán mimo {APP_NAME}, ale existují neuložené změny v {APP_NAME}.<br /><br />Chcete vaše změny zachovat?', 'Hotovo', 'Zrušit', 'Neukládat', 'Uložit', 'Uložit jako…', 'Přepsat', 'Žádné výsledky', 'Najít…', 'Nahradit s…', 'Vše…', 'Další shoda', 'Rozlišovat velká a malá písmena', 'Regulární výraz', 'Nahradit bez možnosti vrátit změny', 'Protože musí být změněno více než {0} souborů, {APP_NAME} změní neotevřené soubory na disku.<br />Nebude možné vrátit změny v těchto souborech.', 'Otevřít soubor', 'Uložit soubor', 'Poznámky k verzi', 'Vše je aktuální!', 'Nahradit', '{0} {1}', 'v <span class=\'dialog-filename\'>{0}</span>', 'Filtr vyloučil všechny soubory {0}', 'výsledek', 'výsledků', ];
  hamster = _0xf45a;
  (function (mink, prairie_dog) {
    var mantis; // _0x3d59bf
    var dogfish; // _0x181257
    
      mantis = _0xf45a;
    while (! ! [])
    {
      try {
        dogfish = - parseInt(mantis(0xac)) * - parseInt(mantis(0xad)) + parseInt(mantis(0xae)) * parseInt(mantis(0xaf)) + parseInt(mantis(0xb0)) + parseInt(mantis(0xb1)) + parseInt(mantis(0xb2)) + - parseInt(mantis(0xb3)) * - parseInt(mantis(0xb4)) + - parseInt(mantis(0xb5));
        if (dogfish === prairie_dog)
          break;
        else
          mink['push'](mink['shift']());
      }
      catch (_0x24ae4e) {
        mink['push'](mink['shift']());
      }
    }
  }(raccoon, 0x92a0a), 
  define({
    "GENERIC_ERROR" : hamster(0xb6),
    "NOT_FOUND_ERR" : hamster(0xb7),
    "NOT_READABLE_ERR" : hamster(0xb8),
    "EXCEEDS_MAX_FILE_SIZE" : 'Soubor větší než {0} MB nemůže být otevřen v aplikaci {APP_NAME}.',
    "NO_MODIFICATION_ALLOWED_ERR" : hamster(0xb9),
    "NO_MODIFICATION_ALLOWED_ERR_FILE" : hamster(0xba),
    "CONTENTS_MODIFIED_ERR" : hamster(0xbb),
    "UNSUPPORTED_ENCODING_ERR" : hamster(0xbc),
    "FILE_EXISTS_ERR" : hamster(0xbd),
    "FILE" : hamster(0xbe),
    "FILE_TITLE" : 'Soubor',
    "DIRECTORY" : hamster(0xbf),
    "DIRECTORY_TITLE" : hamster(0xc0),
    "DIRECTORY_NAMES_LEDE" : hamster(0xc1),
    "FILENAMES_LEDE" : 'Názvy souborů',
    "FILENAME" : hamster(0xc2),
    "DIRECTORY_NAME" : hamster(0xc3),
    "ERROR_LOADING_PROJECT" : 'Chyba při otevírání projektu',
    "OPEN_DIALOG_ERROR" : hamster(0xc4),
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR" : hamster(0xc5),
    "READ_DIRECTORY_ENTRIES_ERROR" : hamster(0xc6),
    "ERROR_OPENING_FILE_TITLE" : hamster(0xc7),
    "ERROR_OPENING_FILE" : hamster(0xc8),
    "ERROR_OPENING_FILES" : hamster(0xc9),
    "ERROR_RELOADING_FILE_TITLE" : hamster(0xca),
    "ERROR_RELOADING_FILE" : 'Došlo k chybě při načítání souboru <span class=\'dialog-filename\'>{0}</span>. {1}',
    "ERROR_SAVING_FILE_TITLE" : 'Chyba při ukládání souboru',
    "ERROR_SAVING_FILE" : hamster(0xcb),
    "ERROR_RENAMING_FILE_TITLE" : hamster(0xcc),
    "ERROR_RENAMING_FILE" : hamster(0xcd),
    "ERROR_DELETING_FILE_TITLE" : 'Chyba při mazání {0}',
    "ERROR_DELETING_FILE" : hamster(0xce),
    "INVALID_FILENAME_TITLE" : hamster(0xcf),
    "INVALID_FILENAME_MESSAGE" : hamster(0xd0),
    "ENTRY_WITH_SAME_NAME_EXISTS" : hamster(0xd1),
    "ERROR_CREATING_FILE_TITLE" : hamster(0xd2),
    "ERROR_CREATING_FILE" : hamster(0xd3),
    "ERROR_MIXED_DRAGDROP" : hamster(0xd4),
    "ERROR_KEYMAP_TITLE" : hamster(0xd5),
    "ERROR_KEYMAP_CORRUPT" : hamster(0xd6),
    "ERROR_LOADING_KEYMAP" : hamster(0xd7),
    "ERROR_RESTRICTED_COMMANDS" : hamster(0xd8),
    "ERROR_RESTRICTED_SHORTCUTS" : hamster(0xd9),
    "ERROR_MULTIPLE_SHORTCUTS" : hamster(0xda),
    "ERROR_DUPLICATE_SHORTCUTS" : 'Tyto příkazy mají stejnou klávesovou zkratku: {0}',
    "ERROR_INVALID_SHORTCUTS" : hamster(0xdb),
    "ERROR_NONEXISTENT_COMMANDS" : hamster(0xdc),
    "ERROR_PREFS_CORRUPT_TITLE" : 'Chyba při čtení nastavení',
    "ERROR_PREFS_CORRUPT" : 'Soubor s nastavením není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát. Pro uložení změn budete muset restartovat aplikaci {APP_NAME}.',
    "ERROR_PROJ_PREFS_CORRUPT" : hamster(0xdd),
    "ERROR_IN_BROWSER_TITLE" : hamster(0xde),
    "ERROR_IN_BROWSER" : '{APP_NAME} je vytvořen v HTML, ale nyní pracuje jako desktopová aplikace, takže ji můžete použít pro úpravu lokálních souborů. Prosím, použijte shell aplikace v repozitáři <b>github.com/adobe/brackets-shell</b> pro spuštění {APP_NAME}.',
    "ERROR_MAX_FILES_TITLE" : hamster(0xdf),
    "ERROR_MAX_FILES" : hamster(0xe0),
    "ERROR_LAUNCHING_BROWSER_TITLE" : hamster(0xe1),
    "ERROR_CANT_FIND_CHROME" : hamster(0xe2),
    "ERROR_LAUNCHING_BROWSER" : hamster(0xe3),
    "LIVE_DEVELOPMENT_ERROR_TITLE" : hamster(0xe4),
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE" : hamster(0xe5),
    "LIVE_DEVELOPMENT_ERROR_MESSAGE" : hamster(0xe6),
    "LIVE_DEV_LOADING_ERROR_MESSAGE" : hamster(0xe7),
    "LIVE_DEV_NEED_HTML_MESSAGE" : hamster(0xe8),
    "LIVE_DEV_NEED_BASEURL_MESSAGE" : 'Pro spuštění živého náhledu se vzdáleným souborem, musíte specifikovat URL pro tento projekt.',
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : hamster(0xe9),
    "LIVE_DEVELOPMENT_INFO_TITLE" : hamster(0xea),
    "LIVE_DEVELOPMENT_INFO_MESSAGE" : hamster(0xeb),
    "LIVE_DEVELOPMENT_TROUBLESHOOTING" : 'Pro více informací navštivte stránku <a href=\'{0}\' title=\'{0}\'>řešení problémů s připojením v Živém náhledu</a>.',
    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : 'Živý náhled',
    "LIVE_DEV_STATUS_TIP_PROGRESS1" : hamster(0xec),
    "LIVE_DEV_STATUS_TIP_PROGRESS2" : hamster(0xed),
    "LIVE_DEV_STATUS_TIP_CONNECTED" : 'Zrušit živý náhled',
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC" : hamster(0xee),
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR" : hamster(0xef),
    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : hamster(0xf0),
    "LIVE_DEV_DETACHED_TARGET_CLOSED" : hamster(0xf1),
    "LIVE_DEV_NAVIGATED_AWAY" : hamster(0xf2),
    "LIVE_DEV_CLOSED_UNKNOWN_REASON" : hamster(0xf3),
    "SAVE_CLOSE_TITLE" : hamster(0xf4),
    "SAVE_CLOSE_MESSAGE" : 'Chcete uložit změny v souboru <span class=\'dialog-filename\'>{0}</span>?',
    "SAVE_CLOSE_MULTI_MESSAGE" : hamster(0xf5),
    "EXT_MODIFIED_TITLE" : 'Externí změny',
    "CONFIRM_DELETE_TITLE" : 'Potvrdit smazání',
    "CONFIRM_FOLDER_DELETE" : hamster(0xf6),
    "FILE_DELETED_TITLE" : hamster(0xf7),
    "EXT_MODIFIED_WARNING" : '<span class=\'dialog-filename\'>{0}</span> byl změněn mimo {APP_NAME}.<br /><br />Chcete uložit soubor a přepsat tyto změny?',
    "EXT_MODIFIED_MESSAGE" : hamster(0xf8),
    "EXT_DELETED_MESSAGE" : hamster(0xf9),
    "DONE" : hamster(0xfa),
    "OK" : 'OK',
    "CANCEL" : hamster(0xfb),
    "DONT_SAVE" : hamster(0xfc),
    "SAVE" : hamster(0xfd),
    "SAVE_AS" : hamster(0xfe),
    "SAVE_AND_OVERWRITE" : hamster(0xff),
    "DELETE" : 'Smazat',
    "BUTTON_YES" : 'Ano',
    "BUTTON_NO" : 'Ne',
    "FIND_MATCH_INDEX" : '{0} z {1}',
    "FIND_NO_RESULTS" : hamster(0x100),
    "FIND_QUERY_PLACEHOLDER" : hamster(0x101),
    "REPLACE_PLACEHOLDER" : hamster(0x102),
    "BUTTON_REPLACE_ALL" : hamster(0x103),
    "BUTTON_REPLACE_ALL_IN_FILES" : 'Nahradit…',
    "BUTTON_REPLACE" : 'Nahradit',
    "BUTTON_NEXT" : '▶',
    "BUTTON_PREV" : '◀',
    "BUTTON_NEXT_HINT" : hamster(0x104),
    "BUTTON_PREV_HINT" : 'Předchozí shoda',
    "BUTTON_CASESENSITIVE_HINT" : hamster(0x105),
    "BUTTON_REGEXP_HINT" : hamster(0x106),
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE" : hamster(0x107),
    "REPLACE_WITHOUT_UNDO_WARNING" : hamster(0x108),
    "BUTTON_REPLACE_WITHOUT_UNDO" : 'Nahradit bez možnosti vrátit změny',
    "OPEN_FILE" : hamster(0x109),
    "SAVE_FILE_AS" : hamster(0x10a),
    "CHOOSE_FOLDER" : 'Vybrat složku',
    "RELEASE_NOTES" : hamster(0x10b),
    "NO_UPDATE_TITLE" : hamster(0x10c),
    "NO_UPDATE_MESSAGE" : 'Verze {APP_NAME} je aktuální.',
    "FIND_REPLACE_TITLE_LABEL" : hamster(0x10d),
    "FIND_REPLACE_TITLE_WITH" : 's',
    "FIND_TITLE_LABEL" : 'Nalezeno',
    "FIND_TITLE_SUMMARY" : '&mdash; {0} {1} {2} v {3}',
    "FIND_NUM_FILES" : hamster(0x10e),
    "FIND_IN_FILES_SCOPED" : hamster(0x10f),
    "FIND_IN_FILES_NO_SCOPE" : 'v projektu',
    "FIND_IN_FILES_ZERO_FILES" : hamster(0x110),
    "FIND_IN_FILES_FILE" : hamster(0xbe),
    "FIND_IN_FILES_FILES" : 'souborech',
    "FIND_IN_FILES_MATCH" : hamster(0x111),
    "FIND_IN_FILES_MATCHES" : hamster(0x112),
    "FIND_IN_FILES_MORE_THAN" : 'více než ',
    "FIND_IN_FILES_PAGING" : '{0}&mdash;{1}',
    "FIND_IN_FILES_FILE_PATH" : hamster(0x113),
    "FIND_IN_FILES_EXPAND_COLLAPSE" : hamster(0x114),
    "FIND_IN_FILES_INDEXING" : hamster(0x115),
    "REPLACE_IN_FILES_ERRORS_TITLE" : hamster(0x116),
    "REPLACE_IN_FILES_ERRORS" : hamster(0x117),
    "ERROR_FETCHING_UPDATE_INFO_TITLE" : hamster(0x118),
    "ERROR_FETCHING_UPDATE_INFO_MSG" : hamster(0x119),
    "NEW_FILE_FILTER" : hamster(0x11a),
    "CLEAR_FILE_FILTER" : hamster(0x11b),
    "NO_FILE_FILTER" : 'Vyloučit soubory…',
    "EXCLUDE_FILE_FILTER" : 'Vyloučit {0}',
    "EDIT_FILE_FILTER" : hamster(0x11c),
    "FILE_FILTER_DIALOG" : hamster(0x11d),
    "FILE_FILTER_INSTRUCTIONS" : hamster(0x11e),
    "FILTER_NAME_PLACEHOLDER" : hamster(0x11f),
    "FILE_FILTER_CLIPPED_SUFFIX" : hamster(0x120),
    "FILTER_COUNTING_FILES" : hamster(0x121),
    "FILTER_FILE_COUNT" : hamster(0x122),
    "FILTER_FILE_COUNT_ALL" : hamster(0x123),
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND" : hamster(0x124),
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES" : hamster(0x125),
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND" : hamster(0x126),
    "ERROR_CSSQUICKEDIT_IDNOTFOUND" : hamster(0x127),
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR" : hamster(0x128),
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX" : hamster(0x129),
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND" : hamster(0x12a),
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND" : 'Rychlá dokumentace není dostupná pro aktuální pozici kurzoru',
    "PROJECT_LOADING" : hamster(0x12b),
    "UNTITLED" : hamster(0x12c),
    "WORKING_FILES" : hamster(0x12d),
    "TOP" : 'Nahoře',
    "BOTTOM" : 'Dole',
    "LEFT" : hamster(0x12e),
    "RIGHT" : hamster(0x12f),
    "CMD_SPLITVIEW_NONE" : 'Bez rozdělení',
    "CMD_SPLITVIEW_VERTICAL" : hamster(0x130),
    "CMD_SPLITVIEW_HORIZONTAL" : hamster(0x131),
    "SPLITVIEW_MENU_TOOLTIP" : hamster(0x132),
    "GEAR_MENU_TOOLTIP" : hamster(0x133),
    "SPLITVIEW_INFO_TITLE" : hamster(0x134),
    "SPLITVIEW_MULTIPANE_WARNING" : hamster(0x135),
    "KEYBOARD_CTRL" : hamster(0x136),
    "KEYBOARD_SHIFT" : hamster(0x137),
    "KEYBOARD_SPACE" : hamster(0x138),
    "KEYBOARD_PAGE_UP" : 'Page Up',
    "KEYBOARD_PAGE_DOWN" : hamster(0x139),
    "KEYBOARD_HOME" : hamster(0x13a),
    "KEYBOARD_END" : hamster(0x13b),
    "KEYBOARD_INSERT" : hamster(0x13c),
    "KEYBOARD_DELETE" : hamster(0x13d),
    "STATUSBAR_CURSOR_POSITION" : hamster(0x13e),
    "STATUSBAR_SELECTION_CH_SINGULAR" : hamster(0x13f),
    "STATUSBAR_SELECTION_CH_PLURAL" : hamster(0x140),
    "STATUSBAR_SELECTION_LINE_SINGULAR" : hamster(0x141),
    "STATUSBAR_SELECTION_LINE_PLURAL" : hamster(0x142),
    "STATUSBAR_SELECTION_MULTIPLE" : hamster(0x143),
    "STATUSBAR_INDENT_TOOLTIP_SPACES" : hamster(0x144),
    "STATUSBAR_INDENT_TOOLTIP_TABS" : hamster(0x145),
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES" : 'Změnit počet mezer použitých pro odsazení',
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS" : hamster(0x146),
    "STATUSBAR_SPACES" : hamster(0x147),
    "STATUSBAR_TAB_SIZE" : 'Velikost tabulátoru:',
    "STATUSBAR_LINE_COUNT_SINGULAR" : 'Řádek: {0}',
    "STATUSBAR_LINE_COUNT_PLURAL" : hamster(0x148),
    "STATUSBAR_USER_EXTENSIONS_DISABLED" : hamster(0x149),
    "STATUSBAR_INSERT" : hamster(0x14a),
    "STATUSBAR_OVERWRITE" : 'OVR',
    "STATUSBAR_INSOVR_TOOLTIP" : hamster(0x14b),
    "STATUSBAR_LANG_TOOLTIP" : 'Klikněte pro změnu typu souboru',
    "STATUSBAR_CODE_INSPECTION_TOOLTIP" : '{0}. Klikněte pro zapnutí panelu zpráv.',
    "STATUSBAR_DEFAULT_LANG" : hamster(0x14c),
    "STATUSBAR_SET_DEFAULT_LANG" : hamster(0x14d),
    "ERRORS_PANEL_TITLE_MULTIPLE" : hamster(0x14e),
    "SINGLE_ERROR" : hamster(0x14f),
    "MULTIPLE_ERRORS" : hamster(0x150),
    "NO_ERRORS" : 'Žádné {0} chyby - dobrá práce!',
    "NO_ERRORS_MULTIPLE_PROVIDER" : hamster(0x151),
    "LINT_DISABLED" : hamster(0x152),
    "NO_LINT_AVAILABLE" : hamster(0x153),
    "NOTHING_TO_LINT" : hamster(0x154),
    "LINTER_TIMED_OUT" : hamster(0x155),
    "LINTER_FAILED" : hamster(0x156),
    "FILE_MENU" : 'Soubor',
    "CMD_FILE_NEW_UNTITLED" : hamster(0x12c),
    "CMD_FILE_NEW" : hamster(0x157),
    "CMD_FILE_NEW_FOLDER" : hamster(0x158),
    "CMD_FILE_OPEN" : 'Otevřít…',
    "CMD_ADD_TO_WORKING_SET" : 'Přidat k pracovní sadě',
    "CMD_OPEN_DROPPED_FILES" : 'Otevřít opuštěné soubory',
    "CMD_OPEN_FOLDER" : 'Otevřít složku…',
    "CMD_FILE_CLOSE" : hamster(0x159),
    "CMD_FILE_CLOSE_ALL" : hamster(0x15a),
    "CMD_FILE_CLOSE_LIST" : hamster(0x15b),
    "CMD_FILE_CLOSE_OTHERS" : hamster(0x15c),
    "CMD_FILE_CLOSE_ABOVE" : hamster(0x15d),
    "CMD_FILE_CLOSE_BELOW" : hamster(0x15e),
    "CMD_FILE_SAVE" : hamster(0xfd),
    "CMD_FILE_SAVE_ALL" : hamster(0x15f),
    "CMD_FILE_SAVE_AS" : hamster(0xfe),
    "CMD_LIVE_FILE_PREVIEW" : 'Živý náhled',
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE" : hamster(0x160),
    "CMD_RELOAD_LIVE_PREVIEW" : hamster(0x161),
    "CMD_PROJECT_SETTINGS" : 'Nastavení projektu…',
    "CMD_FILE_RENAME" : hamster(0x162),
    "CMD_FILE_DELETE" : hamster(0x163),
    "CMD_INSTALL_EXTENSION" : hamster(0x164),
    "CMD_EXTENSION_MANAGER" : hamster(0x165),
    "CMD_FILE_REFRESH" : 'Obnovit',
    "CMD_QUIT" : hamster(0x166),
    "CMD_EXIT" : hamster(0x166),
    "EDIT_MENU" : hamster(0x167),
    "CMD_UNDO" : hamster(0x168),
    "CMD_REDO" : 'Znovu',
    "CMD_CUT" : 'Vyjmout',
    "CMD_COPY" : 'Kopírovat',
    "CMD_PASTE" : hamster(0x169),
    "CMD_SELECT_ALL" : hamster(0x16a),
    "CMD_SELECT_LINE" : hamster(0x16b),
    "CMD_SPLIT_SEL_INTO_LINES" : hamster(0x16c),
    "CMD_ADD_CUR_TO_NEXT_LINE" : hamster(0x16d),
    "CMD_ADD_CUR_TO_PREV_LINE" : 'Přidat kurzor na předcházející řádek',
    "CMD_INDENT" : hamster(0x16e),
    "CMD_UNINDENT" : hamster(0x16f),
    "CMD_DUPLICATE" : hamster(0x170),
    "CMD_DELETE_LINES" : hamster(0x171),
    "CMD_COMMENT" : hamster(0x172),
    "CMD_BLOCK_COMMENT" : hamster(0x173),
    "CMD_LINE_UP" : 'Posunout řádek nahoru',
    "CMD_LINE_DOWN" : hamster(0x174),
    "CMD_OPEN_LINE_ABOVE" : hamster(0x175),
    "CMD_OPEN_LINE_BELOW" : hamster(0x176),
    "CMD_TOGGLE_CLOSE_BRACKETS" : hamster(0x177),
    "CMD_SHOW_CODE_HINTS" : hamster(0x178),
    "FIND_MENU" : hamster(0x179),
    "CMD_FIND" : hamster(0x179),
    "CMD_FIND_NEXT" : hamster(0x17a),
    "CMD_FIND_PREVIOUS" : hamster(0x17b),
    "CMD_FIND_ALL_AND_SELECT" : hamster(0x17c),
    "CMD_ADD_NEXT_MATCH" : 'Přidat další shodu do výběru',
    "CMD_SKIP_CURRENT_MATCH" : hamster(0x17d),
    "CMD_FIND_IN_FILES" : 'Najít v souborech',
    "CMD_FIND_IN_SUBTREE" : hamster(0x17e),
    "CMD_REPLACE" : 'Nahradit',
    "CMD_REPLACE_IN_FILES" : hamster(0x17f),
    "CMD_REPLACE_IN_SUBTREE" : hamster(0x180),
    "VIEW_MENU" : 'Zobrazit',
    "CMD_HIDE_SIDEBAR" : hamster(0x181),
    "CMD_SHOW_SIDEBAR" : hamster(0x182),
    "CMD_TOGGLE_SIDEBAR" : hamster(0x183),
    "CMD_TOGGLE_PANELS" : 'Zobrazit/skrýt panely',
    "CMD_TOGGLE_PURE_CODE" : hamster(0x184),
    "CMD_INCREASE_FONT_SIZE" : 'Zvětšit velikost písma',
    "CMD_DECREASE_FONT_SIZE" : 'Zmenšit velikost písma',
    "CMD_RESTORE_FONT_SIZE" : hamster(0x185),
    "CMD_SCROLL_LINE_UP" : hamster(0x186),
    "CMD_SCROLL_LINE_DOWN" : hamster(0x187),
    "CMD_TOGGLE_LINE_NUMBERS" : hamster(0x188),
    "CMD_TOGGLE_ACTIVE_LINE" : 'Zvýraznit aktivní řádek',
    "CMD_TOGGLE_WORD_WRAP" : hamster(0x189),
    "CMD_LIVE_HIGHLIGHT" : hamster(0x18a),
    "CMD_VIEW_TOGGLE_INSPECTION" : hamster(0x18b),
    "CMD_WORKINGSET_SORT_BY_ADDED" : 'Řadit podle data přidání',
    "CMD_WORKINGSET_SORT_BY_NAME" : hamster(0x18c),
    "CMD_WORKINGSET_SORT_BY_TYPE" : hamster(0x18d),
    "CMD_WORKING_SORT_TOGGLE_AUTO" : hamster(0x18e),
    "CMD_THEMES" : 'Motivy…',
    "NAVIGATE_MENU" : hamster(0x18f),
    "CMD_QUICK_OPEN" : hamster(0x190),
    "CMD_GOTO_LINE" : hamster(0x191),
    "CMD_GOTO_DEFINITION" : hamster(0x192),
    "CMD_GOTO_FIRST_PROBLEM" : 'Přejít na první chybu/varování',
    "CMD_TOGGLE_QUICK_EDIT" : hamster(0x193),
    "CMD_TOGGLE_QUICK_DOCS" : hamster(0x194),
    "CMD_QUICK_EDIT_PREV_MATCH" : hamster(0x195),
    "CMD_QUICK_EDIT_NEXT_MATCH" : 'Další shoda',
    "CMD_CSS_QUICK_EDIT_NEW_RULE" : hamster(0x196),
    "CMD_NEXT_DOC" : hamster(0x197),
    "CMD_PREV_DOC" : hamster(0x198),
    "CMD_NEXT_DOC_LIST_ORDER" : hamster(0x199),
    "CMD_PREV_DOC_LIST_ORDER" : hamster(0x19a),
    "CMD_SHOW_IN_TREE" : hamster(0x19b),
    "CMD_SHOW_IN_EXPLORER" : 'Zobrazit v průzkumníkovi',
    "CMD_SHOW_IN_FINDER" : 'Zobrazit ve vyhledávači',
    "CMD_SHOW_IN_OS" : hamster(0x19c),
    "HELP_MENU" : 'Nápověda',
    "CMD_CHECK_FOR_UPDATE" : hamster(0x19d),
    "CMD_HOW_TO_USE_BRACKETS" : hamster(0x19e),
    "CMD_SUPPORT" : '{APP_NAME} Podpora',
    "CMD_SUGGEST" : hamster(0x19f),
    "CMD_RELEASE_NOTES" : hamster(0x10b),
    "CMD_GET_INVOLVED" : hamster(0x1a0),
    "CMD_SHOW_EXTENSIONS_FOLDER" : hamster(0x1a1),
    "CMD_HEALTH_DATA_STATISTICS" : hamster(0x1a2),
    "CMD_HOMEPAGE" : hamster(0x1a3),
    "CMD_TWITTER" : hamster(0x1a4),
    "CMD_ABOUT" : hamster(0x1a5),
    "CMD_OPEN_PREFERENCES" : hamster(0x1a6),
    "CMD_OPEN_KEYMAP" : hamster(0x1a7),
    "EXPERIMENTAL_BUILD" : hamster(0x1a8),
    "RELEASE_BUILD" : hamster(0x1a9),
    "DEVELOPMENT_BUILD" : hamster(0x1aa),
    "RELOAD_FROM_DISK" : hamster(0x1ab),
    "KEEP_CHANGES_IN_EDITOR" : hamster(0x1ac),
    "CLOSE_DONT_SAVE" : hamster(0x1ad),
    "RELAUNCH_CHROME" : 'Restartovat Chrome',
    "ABOUT" : 'O aplikaci',
    "CLOSE" : hamster(0x159),
    "ABOUT_TEXT_LINE1" : hamster(0x1ae),
    "ABOUT_TEXT_BUILD_TIMESTAMP" : hamster(0x1af),
    "ABOUT_TEXT_LINE3" : 'Oznámení, podmínky týkající se software třetích stran jsou umístěny na stránce <a href=\'{ADOBE_THIRD_PARTY}\'>{ADOBE_THIRD_PARTY}</a> a začleněny prostřednictvím odkazu zde.',
    "ABOUT_TEXT_LINE4" : hamster(0x1b0),
    "ABOUT_TEXT_LINE5" : hamster(0x1b1),
    "ABOUT_TEXT_LINE6" : hamster(0x1b2),
    "ABOUT_TEXT_MDN_DOCS" : hamster(0x1b3),
    "UPDATE_NOTIFICATION_TOOLTIP" : hamster(0x1b4),
    "UPDATE_AVAILABLE_TITLE" : 'Dostupná aktualizace',
    "UPDATE_MESSAGE" : hamster(0x1b5),
    "GET_IT_NOW" : hamster(0x1b6),
    "PROJECT_SETTINGS_TITLE" : hamster(0x1b7),
    "PROJECT_SETTING_BASE_URL" : hamster(0x1b8),
    "PROJECT_SETTING_BASE_URL_HINT" : hamster(0x1b9),
    "BASEURL_ERROR_INVALID_PROTOCOL" : hamster(0x1ba),
    "BASEURL_ERROR_SEARCH_DISALLOWED" : 'URL nemůže obsahovat výrazy pro hledání jako \"{0}\".',
    "BASEURL_ERROR_HASH_DISALLOWED" : hamster(0x1bb),
    "BASEURL_ERROR_INVALID_CHAR" : hamster(0x1bc),
    "BASEURL_ERROR_UNKNOWN_ERROR" : 'Neznámá chyba při zpracování URL',
    "EMPTY_VIEW_HEADER" : '<em>Otevřete soubor, zatímco tento panel je aktivní</em>',
    "FLIPVIEW_BTN_TOOLTIP" : 'Přepnout toto zobrazení na panel {0}',
    "CURRENT_THEME" : hamster(0x1bd),
    "USE_THEME_SCROLLBARS" : 'Použít posuvníky motivu',
    "FONT_SIZE" : hamster(0x1be),
    "FONT_FAMILY" : hamster(0x1bf),
    "THEMES_SETTINGS" : 'Nastavení motivů',
    "BUTTON_NEW_RULE" : hamster(0x196),
    "INSTALL" : 'Instalovat',
    "UPDATE" : hamster(0x1c0),
    "REMOVE" : hamster(0x1c1),
    "DISABLE" : hamster(0x1c2),
    "ENABLE" : hamster(0x1c3),
    "OVERWRITE" : hamster(0xff),
    "CANT_REMOVE_DEV" : hamster(0x1c4),
    "CANT_UPDATE" : hamster(0x1c5),
    "CANT_UPDATE_DEV" : 'Doplňky ve složce \"dev\" nemohou být aktualizovány automaticky.',
    "INSTALL_EXTENSION_TITLE" : 'Instalovat doplněk',
    "UPDATE_EXTENSION_TITLE" : hamster(0x1c6),
    "INSTALL_EXTENSION_LABEL" : hamster(0x1c7),
    "INSTALL_EXTENSION_HINT" : hamster(0x1c8),
    "INSTALLING_FROM" : hamster(0x1c9),
    "INSTALL_SUCCEEDED" : hamster(0x1ca),
    "INSTALL_FAILED" : 'Instalace se nezdařila.',
    "CANCELING_INSTALL" : hamster(0x1cb),
    "CANCELING_HUNG" : hamster(0x1cc),
    "INSTALL_CANCELED" : hamster(0x1cd),
    "VIEW_COMPLETE_DESCRIPTION" : hamster(0x1ce),
    "VIEW_TRUNCATED_DESCRIPTION" : hamster(0x1cf),
    "INVALID_ZIP_FILE" : hamster(0x1d0),
    "INVALID_PACKAGE_JSON" : 'Package.json balíček není platný (chyba byla: {0}).',
    "MISSING_PACKAGE_NAME" : hamster(0x1d1),
    "BAD_PACKAGE_NAME" : hamster(0x1d2),
    "MISSING_PACKAGE_VERSION" : hamster(0x1d3),
    "INVALID_VERSION_NUMBER" : hamster(0x1d4),
    "INVALID_BRACKETS_VERSION" : hamster(0x1d5),
    "DISALLOWED_WORDS" : 'Slova {1} nejsou povolena v {0} poli.',
    "API_NOT_COMPATIBLE" : 'Doplněk není kompatibilní s touto verzí {APP_NAME}. Naleznete jej ve složce disabled extensions.',
    "MISSING_MAIN" : hamster(0x1d6),
    "EXTENSION_ALREADY_INSTALLED" : hamster(0x1d7),
    "EXTENSION_SAME_VERSION" : 'Tento balíček je stejná verze jako ta, kterou již máte nainstalovanou. Chcete přepsat existující doplněk?',
    "EXTENSION_OLDER_VERSION" : hamster(0x1d8),
    "DOWNLOAD_ID_IN_USE" : 'Interní chyba: ID stahování se již používá.',
    "NO_SERVER_RESPONSE" : 'Nelze se připojit na server.',
    "BAD_HTTP_STATUS" : hamster(0x1d9),
    "CANNOT_WRITE_TEMP" : hamster(0x1da),
    "ERROR_LOADING" : 'Při spuštění doplňku došlo k chybě.',
    "MALFORMED_URL" : hamster(0x1db),
    "UNSUPPORTED_PROTOCOL" : 'URL adresa musí být http nebo https.',
    "UNKNOWN_ERROR" : 'Neznámá chyba.',
    "EXTENSION_MANAGER_TITLE" : 'Správce doplňků',
    "EXTENSION_MANAGER_ERROR_LOAD" : hamster(0x1dc),
    "INSTALL_EXTENSION_DRAG" : hamster(0x1dd),
    "INSTALL_EXTENSION_DROP" : hamster(0x1de),
    "INSTALL_EXTENSION_DROP_ERROR" : hamster(0x1df),
    "INSTALL_FROM_URL" : hamster(0x1e0),
    "INSTALL_EXTENSION_VALIDATING" : hamster(0x1e1),
    "EXTENSION_AUTHOR" : hamster(0x1e2),
    "EXTENSION_DATE" : hamster(0x1e3),
    "EXTENSION_INCOMPATIBLE_NEWER" : hamster(0x1e4),
    "EXTENSION_INCOMPATIBLE_OLDER" : hamster(0x1e5),
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER" : hamster(0x1e6),
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER" : hamster(0x1e7),
    "EXTENSION_NO_DESCRIPTION" : 'Bez popisu',
    "EXTENSION_MORE_INFO" : 'Více informací…',
    "EXTENSION_ERROR" : hamster(0x1e8),
    "EXTENSION_KEYWORDS" : hamster(0x1e9),
    "EXTENSION_TRANSLATED_USER_LANG" : hamster(0x1ea),
    "EXTENSION_TRANSLATED_GENERAL" : hamster(0x1eb),
    "EXTENSION_TRANSLATED_LANGS" : 'Tento doplněk byl přeložen do těchto jazyků: {0}',
    "EXTENSION_INSTALLED" : hamster(0x1ec),
    "EXTENSION_UPDATE_INSTALLED" : hamster(0x1ed),
    "EXTENSION_SEARCH_PLACEHOLDER" : hamster(0x1ee),
    "EXTENSION_MORE_INFO_LINK" : hamster(0x1ef),
    "BROWSE_EXTENSIONS" : hamster(0x1f0),
    "EXTENSION_MANAGER_REMOVE" : hamster(0x1f1),
    "EXTENSION_MANAGER_REMOVE_ERROR" : hamster(0x1f2),
    "EXTENSION_MANAGER_UPDATE" : hamster(0x1c6),
    "EXTENSION_MANAGER_UPDATE_ERROR" : hamster(0x1f3),
    "EXTENSION_MANAGER_DISABLE" : hamster(0x1f4),
    "EXTENSION_MANAGER_DISABLE_ERROR" : hamster(0x1f5),
    "MARKED_FOR_REMOVAL" : hamster(0x1f6),
    "UNDO_REMOVE" : hamster(0x168),
    "MARKED_FOR_UPDATE" : hamster(0x1f7),
    "UNDO_UPDATE" : 'Zpět',
    "MARKED_FOR_DISABLING" : hamster(0x1f8),
    "UNDO_DISABLE" : hamster(0x168),
    "CHANGE_AND_RELOAD_TITLE" : hamster(0x1f9),
    "CHANGE_AND_RELOAD_MESSAGE" : hamster(0x1fa),
    "REMOVE_AND_RELOAD" : hamster(0x1fb),
    "CHANGE_AND_RELOAD" : 'Změnit doplňky a restartovat',
    "UPDATE_AND_RELOAD" : hamster(0x1fc),
    "DISABLE_AND_RELOAD" : hamster(0x1fd),
    "PROCESSING_EXTENSIONS" : hamster(0x1fe),
    "EXTENSION_NOT_INSTALLED" : 'Doplněk {0} nemohl být odstraněn, protože nebyl nainstalován.',
    "NO_EXTENSIONS" : hamster(0x1ff),
    "NO_EXTENSION_MATCHES" : hamster(0x200),
    "REGISTRY_SANITY_CHECK_WARNING" : hamster(0x201),
    "EXTENSIONS_INSTALLED_TITLE" : hamster(0x202),
    "EXTENSIONS_AVAILABLE_TITLE" : hamster(0x203),
    "EXTENSIONS_THEMES_TITLE" : 'Motivy',
    "EXTENSIONS_UPDATES_TITLE" : hamster(0x204),
    "INLINE_EDITOR_NO_MATCHES" : hamster(0x205),
    "INLINE_EDITOR_HIDDEN_MATCHES" : hamster(0x206),
    "CSS_QUICK_EDIT_NO_MATCHES" : hamster(0x207),
    "CSS_QUICK_EDIT_NO_STYLESHEETS" : hamster(0x208),
    "IMAGE_VIEWER_LARGEST_ICON" : hamster(0x209),
    "UNIT_PIXELS" : 'pixely',
    "DEBUG_MENU" : hamster(0x20a),
    "ERRORS" : hamster(0x20b),
    "CMD_SHOW_DEV_TOOLS" : hamster(0x20c),
    "CMD_REFRESH_WINDOW" : 'Restartovat {APP_NAME}',
    "CMD_RELOAD_WITHOUT_USER_EXTS" : 'Restartovat bez doplňků',
    "CMD_NEW_BRACKETS_WINDOW" : hamster(0x20d),
    "CMD_LAUNCH_SCRIPT_MAC" : hamster(0x20e),
    "CMD_SWITCH_LANGUAGE" : hamster(0x20f),
    "CMD_RUN_UNIT_TESTS" : 'Spustit testy',
    "CMD_SHOW_PERF_DATA" : hamster(0x210),
    "CMD_ENABLE_NODE_DEBUGGER" : hamster(0x211),
    "CMD_LOG_NODE_STATE" : hamster(0x212),
    "CMD_RESTART_NODE" : hamster(0x213),
    "CMD_SHOW_ERRORS_IN_STATUS_BAR" : hamster(0x214),
    "CMD_OPEN_BRACKETS_SOURCE" : hamster(0x215),
    "CREATING_LAUNCH_SCRIPT_TITLE" : hamster(0x216),
    "ERROR_CREATING_LAUNCH_SCRIPT" : hamster(0x217),
    "ERROR_CLTOOLS_RMFAILED" : hamster(0x218),
    "ERROR_CLTOOLS_MKDIRFAILED" : hamster(0x219),
    "ERROR_CLTOOLS_LNFAILED" : hamster(0x21a),
    "ERROR_CLTOOLS_SERVFAILED" : 'Vnitřní chyba.',
    "ERROR_CLTOOLS_NOTSUPPORTED" : hamster(0x21b),
    "LAUNCH_SCRIPT_CREATE_SUCCESS" : hamster(0x21c),
    "LANGUAGE_TITLE" : hamster(0x20f),
    "LANGUAGE_MESSAGE" : hamster(0x21d),
    "LANGUAGE_SUBMIT" : hamster(0x21e),
    "LANGUAGE_CANCEL" : hamster(0xfb),
    "LANGUAGE_SYSTEM_DEFAULT" : 'Výchozí',
    "HEALTH_DATA_NOTIFICATION" : hamster(0x21f),
    "HEALTH_FIRST_POPUP_TITLE" : hamster(0x220),
    "HEALTH_DATA_DO_TRACK" : 'Sdílejte anonymní informace o používání {APP_NAME}',
    "HEALTH_DATA_NOTIFICATION_MESSAGE" : hamster(0x221),
    "HEALTH_DATA_PREVIEW" : hamster(0x220),
    "HEALTH_DATA_PREVIEW_INTRO" : hamster(0x222),
    "INLINE_TIMING_EDITOR_TIME" : hamster(0x223),
    "INLINE_TIMING_EDITOR_PROGRESSION" : 'Postup',
    "BEZIER_EDITOR_INFO" : hamster(0x224),
    "STEPS_EDITOR_INFO" : hamster(0x225),
    "INLINE_TIMING_EDITOR_INVALID" : hamster(0x226),
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP" : hamster(0x227),
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP" : hamster(0x228),
    "COLOR_EDITOR_RGBA_BUTTON_TIP" : hamster(0x229),
    "COLOR_EDITOR_HEX_BUTTON_TIP" : hamster(0x22a),
    "COLOR_EDITOR_HSLA_BUTTON_TIP" : hamster(0x22b),
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR" : hamster(0x22c),
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL" : '{0} (použito {1} krát)',
    "CMD_JUMPTO_DEFINITION" : hamster(0x192),
    "CMD_SHOW_PARAMETER_HINT" : hamster(0x22d),
    "NO_ARGUMENTS" : hamster(0x22e),
    "DETECTED_EXCLUSION_TITLE" : hamster(0x22f),
    "DETECTED_EXCLUSION_INFO" : '{APP_NAME} narazil na problémy při zpracování <span class=\'dialog-filename\'>{0}</span>.<br><br>Tento soubor nebude nadále používat nápovědy kódu, přechod na definici nebo rychlou úpravu. Pro opětovné zapnutí těchto funkcí, otevřete <code>.brackets.json</code> ve vašem projektu a upravte <code>jscodehints.detectedExclusions</code>.<br><br>Pravděpodobně je to chyba {APP_NAME}. Pokud můžete poskytnout kopii tohoto souboru, prosíme <a href=\'https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue\'>nahlaste tuto chybu</a> s odkazem na daný soubor.',
    "JSLINT_NAME" : hamster(0x230),
    "CMD_ENABLE_QUICK_VIEW" : hamster(0x231),
    "CMD_TOGGLE_RECENT_PROJECTS" : hamster(0x232),
    "DOCS_MORE_LINK" : hamster(0x1ef),
    "COLLAPSE_ALL" : hamster(0x233),
    "EXPAND_ALL" : hamster(0x234),
    "COLLAPSE_CURRENT" : hamster(0x235),
    "EXPAND_CURRENT" : hamster(0x236),
    "DESCRIPTION_CLOSE_BRACKETS" : 'true k automatickému uzavírání závorek',
    "DESCRIPTION_CLOSE_OTHERS_ABOVE" : hamster(0x237),
    "DESCRIPTION_CLOSE_OTHERS_BELOW" : hamster(0x238),
    "DESCRIPTION_CLOSE_OTHERS" : hamster(0x239),
    "DESCRIPTION_CLOSE_TAGS" : hamster(0x23a),
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS" : hamster(0x23b),
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING" : hamster(0x23c),
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING" : 'Zavřít, pokud je napsán / uzavírací značky',
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS" : hamster(0x23d),
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : hamster(0x23e),
    "DESCRIPTION_CODE_FOLDING_ENABLED" : hamster(0x23f),
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER" : hamster(0x240),
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL" : hamster(0x241),
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE" : 'Nejmenší počet řádků, pro které se objeví ikona pro skrytí kódu',
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES" : hamster(0x242),
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE" : hamster(0x243),
    "DESCRIPTION_ATTR_HINTS" : 'Povolit/zakázat nápovědy HTML vlastností',
    "DESCRIPTION_CSS_PROP_HINTS" : hamster(0x244),
    "DESCRIPTION_JS_HINTS" : 'Povolit/zakázat nápovědy v JavaScriptu',
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS" : hamster(0x245),
    "DESCRIPTION_PREF_HINTS" : hamster(0x246),
    "DESCRIPTION_SPECIAL_CHAR_HINTS" : hamster(0x247),
    "DESCRIPTION_SVG_HINTS" : 'Povolit/zakázat nápovědy v SVG',
    "DESCRIPTION_HTML_TAG_HINTS" : hamster(0x248),
    "DESCRIPTION_URL_CODE_HINTS" : 'Povolit/zakázat nápovědy adres URL v HTML & CSS/LESS/SCSS',
    "DESCRIPTION_DRAG_DROP_TEXT" : hamster(0x249),
    "DESCRIPTION_HEALTH_DATA_TRACKING" : hamster(0x24a),
    "DESCRIPTION_HIGHLIGHT_MATCHES" : 'Povolit automatické zvýrazňování shodujících se výrazů v celém dokumentu',
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN" : hamster(0x24b),
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY" : 'Zvýraznit pouze pokud je výběr kompletním výrazem',
    "DESCRIPTION_INSERT_HINT_ON_TAB" : hamster(0x24c),
    "DESCRIPTION_NO_HINTS_ON_DOT" : hamster(0x24d),
    "DESCRIPTION_JSLINT_OPTIONS" : 'Objekt s výchozími možnostmi pro JSLint',
    "DESCRIPTION_JSLINT_OPTIONS_ASS" : hamster(0x24e),
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE" : hamster(0x24f),
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER" : 'true pokud by globální proměnné standardního prohlížeče měly být předdefinované',
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE" : hamster(0x250),
    "DESCRIPTION_JSLINT_OPTIONS_CONTINUE" : 'true k povolení příkazu \"continue\"',
    "DESCRIPTION_JSLINT_OPTIONS_COUCH" : hamster(0x251),
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG" : hamster(0x252),
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL" : hamster(0x253),
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ" : hamster(0x254),
    "DESCRIPTION_JSLINT_OPTIONS_ES6" : hamster(0x255),
    "DESCRIPTION_JSLINT_OPTIONS_EVIL" : 'true k povolení eval',
    "DESCRIPTION_JSLINT_OPTIONS_FORIN" : 'true k povolení nefiltrovaných \"for ... in\"',
    "DESCRIPTION_JSLINT_OPTIONS_INDENT" : hamster(0x256),
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR" : hamster(0x257),
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN" : 'Maximální počet znaků na řádku',
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP" : hamster(0x258),
    "DESCRIPTION_JSLINT_OPTIONS_NODE" : hamster(0x259),
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN" : 'true k povolení přebývajících podtržítek v identifikátorech',
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL" : hamster(0x25a),
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS" : hamster(0x25b),
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP" : hamster(0x25c),
    "DESCRIPTION_JSLINT_OPTIONS_RHINO" : hamster(0x25d),
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY" : hamster(0x25e),
    "DESCRIPTION_JSLINT_OPTIONS_STUPID" : hamster(0x25f),
    "DESCRIPTION_JSLINT_OPTIONS_SUB" : hamster(0x260),
    "DESCRIPTION_JSLINT_OPTIONS_TODO" : hamster(0x261),
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM" : 'true k povolení nepoužitých parametrů',
    "DESCRIPTION_JSLINT_OPTIONS_VARS" : hamster(0x262),
    "DESCRIPTION_JSLINT_OPTIONS_WHITE" : 'true k ignorování pravidel ohledně prázdných znaků',
    "DESCRIPTION_LANGUAGE" : hamster(0x263),
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS" : hamster(0x264),
    "DESCRIPTION_LANGUAGE_FILE_NAMES" : 'Dodatečná mapování z názvu souboru na jméno jazyka',
    "DESCRIPTION_LINTING_ENABLED" : 'true k povolení panelu zpráv',
    "DESCRIPTION_ASYNC_TIMEOUT" : 'Čas v milisekundách, po kterém vyprší asynchronní lintery',
    "DESCRIPTION_LINTING_PREFER" : hamster(0x265),
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER" : hamster(0x266),
    "DESCRIPTION_USE_PREFERED_ONLY" : hamster(0x267),
    "DESCRIPTION_MAX_CODE_HINTS" : hamster(0x268),
    "DESCRIPTION_PATH" : hamster(0x269),
    "DESCRIPTION_PROXY" : 'URL proxy serveru použitého k instalaci doplňků',
    "DESCRIPTION_SCROLL_PAST_END" : hamster(0x26a),
    "DESCRIPTION_SHOW_CODE_HINTS" : hamster(0x26b),
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING" : hamster(0x26c),
    "DESCRIPTION_SHOW_LINE_NUMBERS" : hamster(0x26d),
    "DESCRIPTION_SMART_INDENT" : hamster(0x26e),
    "DESCRIPTION_SOFT_TABS" : hamster(0x26f),
    "DESCRIPTION_SORT_DIRECTORIES_FIRST" : hamster(0x270),
    "DESCRIPTION_SPACE_UNITS" : 'Počet mezer použitých v odsazení mezerami',
    "DESCRIPTION_STATIC_SERVER_PORT" : hamster(0x271),
    "DESCRIPTION_STYLE_ACTIVE_LINE" : 'true ke zvýraznění řádku, na kterém se nachází kurzor, barvou na pozadí',
    "DESCRIPTION_TAB_SIZE" : hamster(0x272),
    "DESCRIPTION_USE_TAB_CHAR" : hamster(0x273),
    "DESCRIPTION_UPPERCASE_COLORS" : hamster(0x274),
    "DESCRIPTION_WORD_WRAP" : 'Zalomit řádky přesahující šířku viewportu',
    "DESCRIPTION_DETECTED_EXCLUSIONS" : hamster(0x275),
    "DESCRIPTION_INFERENCE_TIMEOUT" : hamster(0x276),
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR" : hamster(0x277),
    "DESCRIPTION_QUICK_VIEW_ENABLED" : hamster(0x278),
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW" : hamster(0x279),
    "DESCRIPTION_THEME" : hamster(0x27a),
    "DESCRIPTION_USE_THEME_SCROLLBARS" : hamster(0x27b),
    "DESCRIPTION_LINTING_COLLAPSED" : 'true ke skrytí panelu linteru',
    "DESCRIPTION_FONT_FAMILY" : hamster(0x27c),
    "DESCRIPTION_FONT_SIZE" : hamster(0x27d),
    "DESCRIPTION_FIND_IN_FILES_NODE" : hamster(0x27e),
    "DESCRIPTION_FIND_IN_FILES_INSTANT" : hamster(0x27f),
    "DESCRIPTION_FONT_SMOOTHING" : hamster(0x280),
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW" : hamster(0x281),
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE" : hamster(0x282),
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED" : hamster(0x283),
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS" : hamster(0x284),
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT" : hamster(0x285),
    "DEFAULT_PREFERENCES_JSON_DEFAULT" : 'Výchozí',
    "DESCRIPTION_PURE_CODING_SURFACE" : hamster(0x286)
  }));
  