'use strict';
var _0xe511 = ["NEWwa", "defer", "promise", "reject", "$$timeoutId", "$apply", "TqmGc", "cancel", "ZzEHk", "split", "ANRZn", "hasOwnProperty", "Tlbqb", "DJERx", "qmtFk", "518396ZLSoWP", "169311VVLPvd", "2HDESuW", "624208rlyKCF", "497818xECyoc", "87002JCynXT", "1KxXkbE", "301269KDSEzX", "1680580xcBkty", "$timeout", "5|7|8|2|3|1|6|0|4", "canceled", "badprom", "`$timeout.cancel()` called with a promise that was not generated by `$timeout()`.", "$rootScope", "$get", "AZxiR", "$browser", "lYylt", "$exceptionHandler"];
var _0x47e9e9 = _0xe977;
(function(data, val) {
  var toMonths = _0xe977;
  for (; !![];) {
    try {
      var nodeval = parseInt(toMonths(373)) + -parseInt(toMonths(374)) * parseInt(toMonths(375)) + -parseInt(toMonths(376)) + -parseInt(toMonths(377)) + -parseInt(toMonths(378)) + -parseInt(toMonths(379)) * parseInt(toMonths(380)) + parseInt(toMonths(381));
      if (nodeval === val) {
        break;
      } else {
        data["push"](data["shift"]());
      }
    } catch (_0x78928a) {
      data["push"](data["shift"]());
    }
  }
})(_0xe511, -16039 * 4 + 485419 + -71206);
function _0xe977(totalExpectedResults, entrySelector) {
  return _0xe977 = function(hashOrKey, value) {
    hashOrKey = hashOrKey - (6782 + -9688 + 3279);
    var _0x65a294 = _0xe511[hashOrKey];
    return _0x65a294;
  }, _0xe977(totalExpectedResults, entrySelector);
}
var $timeoutMinErr = minErr(_0x47e9e9(382));
function $TimeoutProvider() {
  var findMiddlePosition = _0x47e9e9;
  var nodes = {
    "ZzEHk" : findMiddlePosition(383),
    "IKSjQ" : function(saveNotifs, notifications) {
      return saveNotifs(notifications);
    },
    "ANRZn" : findMiddlePosition(384),
    "Tlbqb" : function(require, load, callback) {
      return require(load, callback);
    },
    "DJERx" : findMiddlePosition(385),
    "qmtFk" : findMiddlePosition(386),
    "NEWwa" : "$timeout",
    "AZxiR" : findMiddlePosition(387),
    "lYylt" : "$$q"
  };
  this[findMiddlePosition(388)] = [nodes[findMiddlePosition(389)], findMiddlePosition(390), "$q", nodes[findMiddlePosition(391)], findMiddlePosition(392), function($_GET, options, text, newval, unsafeTermFn) {
    function init(fn, params, key) {
      var parseInt = getIndexForNode;
      if (!isFunction(fn)) {
        key = params;
        params = fn;
        fn = noop;
      }
      var args = sliceArgs(arguments, 7146 + -9421 + 2278);
      var isInput = isDefined(key) && !key;
      var state = (isInput ? newval : text)[parseInt(394)]();
      var obj = state[parseInt(395)];
      var i;
      return i = options[parseInt(394)](function() {
        var decode = parseInt;
        try {
          state["resolve"](fn["apply"](null, args));
        } catch (setArgName) {
          state[decode(396)](setArgName);
          unsafeTermFn(setArgName);
        } finally {
          delete result[obj[decode(397)]];
        }
        if (!isInput) {
          $_GET[decode(398)]();
        }
      }, params, frontpageItems[parseInt(399)]), obj[parseInt(397)] = i, result[i] = state, obj;
    }
    var getIndexForNode = findMiddlePosition;
    var frontpageItems = {
      "TqmGc" : nodes[getIndexForNode(393)]
    };
    var result = {};
    return init[getIndexForNode(400)] = function(index) {
      var parseInt = getIndexForNode;
      var callbackVals = nodes[parseInt(401)][parseInt(402)]("|");
      var callbackCount = 1525 * 4 + -247 * -31 + -1 * 13757;
      for (; !![];) {
        switch(callbackVals[callbackCount++]) {
          case "0":
            delete result[letter];
            continue;
          case "1":
            nodes["IKSjQ"](markQExceptionHandled, data[parseInt(395)]);
            continue;
          case "2":
            var letter = index[parseInt(397)];
            continue;
          case "3":
            var data = result[letter];
            continue;
          case "4":
            return options["defer"][parseInt(400)](letter);
          case "5":
            if (!index) {
              return ![];
            }
            continue;
          case "6":
            data[parseInt(396)](nodes[parseInt(403)]);
            continue;
          case "7":
            if (!index[parseInt(404)]("$$timeoutId")) {
              throw nodes[parseInt(405)]($timeoutMinErr, nodes[parseInt(406)], nodes[parseInt(407)]);
            }
            continue;
          case "8":
            if (!result[parseInt(404)](index[parseInt(397)])) {
              return ![];
            }
            continue;
        }
        break;
      }
    }, init;
  }];
}
;
