'use strict';

const _0xe511 = ['NEWwa', 'defer', 'promise', 'reject', '$$timeoutId', '$apply', 'TqmGc', 'cancel', 'ZzEHk', 'split', 'ANRZn', 'hasOwnProperty', 'Tlbqb', 'DJERx', 'qmtFk', '518396ZLSoWP', '169311VVLPvd', '2HDESuW', '624208rlyKCF', '497818xECyoc', '87002JCynXT', '1KxXkbE', '301269KDSEzX', '1680580xcBkty', '$timeout', '5|7|8|2|3|1|6|0|4', 'canceled', 'badprom', '`$timeout.cancel()` called with a promise that was not generated by `$timeout()`.', '$rootScope', '$get', 'AZxiR', '$browser', 'lYylt', '$exceptionHandler'];
const _0x47e9e9 = _0xe977;

(function (_0x1b50b1, _0x50e042) {
    const _0x3c3cd4 = _0xe977;

    while (true) {
        try {
            const _0x1b098c = parseInt(_0x3c3cd4(0x175)) + -parseInt(_0x3c3cd4(0x176)) * parseInt(_0x3c3cd4(0x177)) + -parseInt(_0x3c3cd4(0x178)) + -parseInt(_0x3c3cd4(0x179)) + -parseInt(_0x3c3cd4(0x17a)) + -parseInt(_0x3c3cd4(0x17b)) * parseInt(_0x3c3cd4(0x17c)) + parseInt(_0x3c3cd4(0x17d));

            if (_0x1b098c === _0x50e042) break;else _0x1b50b1.push(_0x1b50b1.shift());
        } catch (_0x78928a) {
            _0x1b50b1.push(_0x1b50b1.shift());
        }
    }
})(_0xe511, 350057);
function _0xe977(_0x4678d3, _0x544851) {
    return _0xe977 = function (_0x204349, _0x2da164) {
        _0x204349 = _0x204349 - 373;
        const _0x65a294 = _0xe511[_0x204349];

        return _0x65a294;
    }, _0xe977(_0x4678d3, _0x544851);
}
const $timeoutMinErr = minErr(_0x47e9e9(0x17e));

function $TimeoutProvider() {
    const _0x5ba314 = _0x47e9e9;
    const _0x3374c1 = {
        'ZzEHk': _0x5ba314(0x17f),
        'IKSjQ': function (_0x4fea6e, _0x5b0d90) {
            return _0x4fea6e(_0x5b0d90);
        },
        'ANRZn': _0x5ba314(0x180),
        'Tlbqb': function (_0x3f4a98, _0x598ed2, _0x237540) {
            return _0x3f4a98(_0x598ed2, _0x237540);
        },
        'DJERx': _0x5ba314(0x181),
        'qmtFk': _0x5ba314(0x182),
        'NEWwa': '$timeout',
        'AZxiR': _0x5ba314(0x183),
        'lYylt': '$$q'
    };

    this[_0x5ba314(0x184)] = [_0x3374c1[_0x5ba314(0x185)], _0x5ba314(0x186), '$q', _0x3374c1[_0x5ba314(0x187)], _0x5ba314(0x188), function (_0x2b467d, _0x25f14e, _0x41ad8d, _0x4614a9, _0x3520d9) {
        const _0x410b7f = _0x5ba314;
        const _0x185e77 = { 'TqmGc': _0x3374c1[_0x410b7f(0x189)] };
        const _0x159562 = {};

        function _0xc72016(_0x4020d9, _0x312dd0, _0x16acec) {
            const _0x5429c2 = _0x410b7f;

            !isFunction(_0x4020d9) && (_0x16acec = _0x312dd0, _0x312dd0 = _0x4020d9, _0x4020d9 = noop);

            const _0x22ad15 = sliceArgs(arguments, 3);

            const _0x3181e3 = isDefined(_0x16acec) && !_0x16acec;

            const _0x3b2cac = (_0x3181e3 ? _0x4614a9 : _0x41ad8d)[_0x5429c2(0x18a)]();

            const _0x5972e4 = _0x3b2cac[_0x5429c2(0x18b)];

            var _0x40f5e4;

            return _0x40f5e4 = _0x25f14e[_0x5429c2(0x18a)](function () {
                const _0x190a7f = _0x5429c2;

                try {
                    _0x3b2cac.resolve(_0x4020d9.apply(null, _0x22ad15));
                } catch (_0x1c7fa1) {
                    _0x3b2cac[_0x190a7f(0x18c)](_0x1c7fa1), _0x3520d9(_0x1c7fa1);
                } finally {
                    delete _0x159562[_0x5972e4[_0x190a7f(0x18d)]];
                }
                if (!_0x3181e3) _0x2b467d[_0x190a7f(0x18e)]();
            }, _0x312dd0, _0x185e77[_0x5429c2(0x18f)]), _0x5972e4[_0x5429c2(0x18d)] = _0x40f5e4, _0x159562[_0x40f5e4] = _0x3b2cac, _0x5972e4;
        }
        return _0xc72016[_0x410b7f(0x190)] = function (_0x472a7e) {
            const _0x2bb7b5 = _0x410b7f;

            const _0x460051 = _0x3374c1[_0x2bb7b5(0x191)][_0x2bb7b5(0x192)]('|');

            var _0x43a6e4 = 0;

            while (true) {
                switch (_0x460051[_0x43a6e4++]) {
                    case '0':
                        delete _0x159562[_0x3ee75e];
                        continue;
                    case '1':
                        _0x3374c1.IKSjQ(markQExceptionHandled, _0x301abc[_0x2bb7b5(0x18b)]);
                        continue;
                    case '2':
                        const _0x3ee75e = _0x472a7e[_0x2bb7b5(0x18d)];

                        continue;
                    case '3':
                        const _0x301abc = _0x159562[_0x3ee75e];

                        continue;
                    case '4':
                        return _0x25f14e.defer[_0x2bb7b5(0x190)](_0x3ee75e);
                    case '5':
                        if (!_0x472a7e) return false;
                        continue;
                    case '6':
                        _0x301abc[_0x2bb7b5(0x18c)](_0x3374c1[_0x2bb7b5(0x193)]);
                        continue;
                    case '7':
                        if (!_0x472a7e[_0x2bb7b5(0x194)]('$$timeoutId')) throw _0x3374c1[_0x2bb7b5(0x195)]($timeoutMinErr, _0x3374c1[_0x2bb7b5(0x196)], _0x3374c1[_0x2bb7b5(0x197)]);
                        continue;
                    case '8':
                        if (!_0x159562[_0x2bb7b5(0x194)](_0x472a7e[_0x2bb7b5(0x18d)])) return false;
                        continue;
                }
                break;
            }
        }, _0xc72016;
    }];
}
